### ISSUE TITLE
Adding a H-Scene POV Mode

### ISSUE THREAD

**Issue by DooMGuy87** [aa2g/AA2Unlimited#1]
I was wondering if it would be posible to add a POV mode in H-Scenes like some modders added to the most recent (and some older) ILLUSION games. This would be a great addition to the game.
The idea would be, pressing a button, switches between the guy to girl POV or the active girl to passive girl POV in case of yuri.
Thank you for your work with AAFace and now with this project, I hope you can add this and other cool features!

**Comment by AA2Hackanon** [comment]
That was a grim reminder of how much i suck at math.
Somewhat added now, gonna release it with the next version
