### ISSUE TITLE
4k Resolution and message on startup

### ISSUE THREAD

**Issue by Dune02** [aa2g/AA2Unlimited#100]
I receive the following when trying to start the game at any resolution above 1920x1080. This is new after update 1.0. Tried deleting AAU folder and repatching an unmodded exe to no avail. Game used to run in 3840x2160 with no issues. Now i get this message and it runs in 1080.
<img width="527" alt="untitled" src="https://user-images.githubusercontent.com/39396621/40216509-07a82d5e-5a1c-11e8-8fb5-7894ad3a4bfa.png">

**Comment by dimamatik** [comment]
Maybe Windos 10 Scale issue. For default, on large display, the system will scale any application by 150%-200%. You can change this on settings (right click/compatibility tab)

**Comment by Dune02** [comment]
I run windows 7. You were correct. Under compatiablity check disable scaling on high dpi setting and it worked perfectly. Thanks this has been driving me up a wall.
