### ISSUE TITLE
Male Hair Crashes + H AI Questions

### ISSUE THREAD

**Issue by luciki** [aa2g/AA2Unlimited#101]
Hello,

With homosex enabled, both me and my friend get the [same error](https://i.gyazo.com/07358cb028d83b6071c56e50364961a8.png) where the finishing positions do not actually climax. Leaving the H scene simply crashes the game. I can provide the dump log if necessary. We both had used the More Cumming Positions mod and then a clean reinstall without it, with the same error no matter what. This has been tried with the fixes option in unlock and without it as well.

Another question I had was regarding how AAU and AA2 initializes H-scenes with f/f couples. Sometimes I get H-AI scenes where the PC is the active partner (usually evil H-AI), and other scenes where the PC is the passive partner (large chance in forced H-AI, but sometimes the PC is active; seems to depend on the NPC). What exactly triggers this? I know when an NPC asks the PC for H, it does seem to also randomize who starts as the active partner and who starts as the passive partner.  

Is it possible to some day add an option to toggle H-AI without it having to specifically be a forced/evil or module related scene? Such as in AA1, asking the NPC a certain option did make the scene AI-controlled.

**Comment by luciki** [comment]
Found the issue on my own-- it is due to assigning extra hairs via AAU onto male characters. Any extra hair causes the game to crash in multiple ways, either when editing the clothes, talking, or during H scenes (no matter what pairing type).

**Comment by geneishouko** [comment]
The starting positions for f/f sex depend on whether the interaction is public or private and who starts the interaction. It isn't random.

It is possible to expand the scope of H-AI but there is no work going on towards that.
