### ISSUE TITLE
Uncensor not working

### ISSUE THREAD

**Issue by slan27** [aa2g/AA2Unlimited#115]
Hi I downloaded the AA2mini and added the MK-III clothing and uncensor but it's still not working. I'll attach an image with my installed mods

![aa2install v7 1 2018-09-22 18 34 03](https://user-images.githubusercontent.com/43494112/45916297-35b18b80-be96-11e8-870c-09e6f926e20b.jpg)

**Comment by geneishouko** [comment]
Wizzard and AA2Install mods generally don't work with AA2Mini. Read the FAQ and scroll down to where it addresses this issue, it will get you two links from which you can download some mods for AA2Mini.

[[FAQ](https://pastebin.com/bhrA6iGx)] https://pastebin.com/bhrA6iGx
