### ISSUE TITLE
Win 10 fix broken as of new Windows 10 October

### ISSUE THREAD

**Issue by khaosdvorak** [aa2g/AA2Unlimited#119]
The AA2Unlimited Windows 10 fps fix no longer works as of the latest version of Windows.

Note that this update was pulled from Windows update earlier this month due to it deleting peoples files after installing via Windows update, so most people don't have an issue yet. I encountered the problem by using a new Windows 10 LTSC ISO during a clean install. The updates will be pushed to others in the coming months.

Without the fix enabled, the game runs, just with the low fps issue.

The included zip file has the aaucrash.dmp file as well as both new d3d9.dll files from system32 and syswow64 folders.
[aa2crashdumps.zip](https://github.com/aa2g/AA2Unlimited/files/2523195/aa2crashdumps.zip)

**Comment by geneishouko** [comment]
Disable win10fix in the launcher and try enabling wined3d instead.

**Comment by lolimanz** [comment]
Well that seems to fix the low fps, but the graphics are borked. Win 10, 8GB of ram, and a 780TI with latest drivers.

![capture](https://user-images.githubusercontent.com/43864273/47621716-38755100-dad2-11e8-8e2e-863a2e534bda.JPG)

**Comment by geneishouko** [comment]
What version of nvidia drivers? Can you try an older version? Someone else commented that it was not the windows update that broke the graphics.

**Comment by lolimanz** [comment]
Currently on the 416.34 nvidia drivers. I can try some older ones and see if it helps.

**Comment by lolimanz** [comment]
I can confirm that the 399.24 nvidia drivers (2018.9.10 release date) drivers work as they should, the regular FPS fix in AA2Unlimited works again. Seems that the 4xx series of drivers have the changes that effect the game.

Thanks for your time, I didn't suspect the Nvidia drivers as the culprit.

**Comment by geneishouko** [comment]
Nice. Thank you for your time too.

**Comment by linkanon** [comment]
reopened until not an issue

**Comment by ark-royal-91** [comment]
In the meantime, you can sidestep broken graphics with wined3d by turning off the type 2 renderer.
