### ISSUE TITLE
Freezing H-Compatibility Values

### ISSUE THREAD

**Issue by DooMGuy87** [aa2g/AA2Unlimited#12]
As you may know, if you have multiple h partners, its almost impossible to have all the poses availible with them wthout modding the H-style.lst file or editing the values with a save editor or the AA2 Trainer.
Would it possible to add an option that let the h-compat. values to increase normally and freeze them in a way that they never decrease, even if you have more than a h-partner?

**Comment by linkanon** [comment]
You can do it by simply going out with your H partners. If you're a couple compatibility does not decay over time. Alternatives are, as you suggested, using an unlocked `H-style.lst` or setting max compatibility through `ReiEdit`/`AA2Trainer`. I honestly see no reason to add this feature to AAU unless there's something more that is not covered by other methods.

**Comment by DooMGuy87** [comment]
I see, I always felt the point decay with multiple partners in the vanilla game was just stupid, but they maybe added that function to simulate that your character is tired and unable to do certain poses after having too much h I suppose.
BTW I'll just maybe stick with the AA2 trainer thing, it´s better than having all the poses available from the start... Thanks for your response!

**Comment by linkanon** [comment]
Not tiredness but literally compatibility. If you don't H regularly you don't know what makes your partner tick.
That and to give you a reason to go out with non-singlemindeds(or sluts but their sex drive easily compensates for the decay)
If you don't want all poses unlocked but want some specific ones you can edit the H-style.lst to make some positions available.
