### ISSUE TITLE
can't play in fullscreen mode

### ISSUE THREAD

**Issue by aethelred175** [aa2g/AA2Unlimited#129]
1.downloaded aa2unlimited
2.patching
3.done
4.play aa2 and launcher show with some features
5.i make try and work
6.i want to play it in fulscreen without borderless or whatever, just fullscreen
7.long loading, blank screen, and program not responding.
any help?

**Comment by Scout25DA** [comment]
> 1.downloaded aa2unlimited
> 2.patching
> 3.done
> 4.play aa2 and launcher show with some features
> 5.i make try and work
> 6.i want to play it in fulscreen without borderless or whatever, just fullscreen
> 7.long loading, blank screen, and program not responding.
> any help?

I'm sorry, but unfortunately full screen is bad thing to be honest.... You might better get used to borderless because for example in borderless version you can freely Alt+Tab while for full screen it causes black screen and crash.
