### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AldebaraanMKII** [aa2g/AA2Unlimited#131]
https://mega.nz/#!dYYjmQRJ!-RINMjmjgBLji9ukAgJMxKta2BNgbrOLdSv6A3wRBDs
Game crashes after some time in the second period. No problem occurs in the first. Always the second. I tried increasing the buffer sizes since that fixed a crash i had with the editor but to no avail.
I'm using v1.3 with AA2 Mini btw.

Edit: I reduced the buffer size to 800/150/150 and now i crash in the third period.

**Comment by geneishouko** [comment]
The crash dump you sent doesn't seem to indicate it's an AAU crash. There's very little we can do about that. Maybe if you tell us more about your OS and graphics card we may have a clue.

**Comment by AldebaraanMKII** [comment]
Windows 7 
i3 3220
gtx 750 ti
8gb 1333mhz DDR3

In my previous installation of AA2 (before going to mini) i had AA2U 0.6.3 and with the same class and never had any crash at all.

**Comment by AldebaraanMKII** [comment]
64 bits
Yes it exists
https://pastebin.com/yxntah7s

**Comment by geneishouko** [comment]
Recently we found that disabling *win10fix* and enabling *wined3d* and *software vertex processing* fixes several NVIDIA crashes.

**Comment by kayfour** [comment]
Have you tried the [suggested fixes](https://github.com/aa2g/AA2Unlimited/wiki#i-have-nvidia-crashes-or-glitches-help) for NVIDIA crashes yet?
