### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by MysticMole** [aa2g/AA2Unlimited#132]
The game crashes at random intervals. I can sometimes play for up to an hour with no issues before getting a crash and sometimes it will crash within minutes of starting a game. I opened the crashdump and ran the .ecxr command and it said it was unable to verify AAUnlimitedDDL,ddl. I have next to know knowledge of debugging so this information is useless to me so any help from someone who knows what they're doing would be greatly appreciated. I should point out that I recently updated to version 1.3 AAUnlimited but the crashes occurred in the two prior versions as well. I installed the game with AAMini and followed the instructions to the latter so I don't think it's a problem with my install. I've attached the bug report, so hopefully someone can help me out.
[Crash.zip](https://github.com/aa2g/AA2Unlimited/files/2717630/Crash.zip)

**Comment by SaotomeRanma142** [comment]
I'm also getting random crashes that have been happening across multiple versions of AAU. They just happen, when I am not interacting with any characters. Crash dump is attached.
[c0000005.zip](https://github.com/aa2g/AA2Unlimited/files/2777306/c0000005.zip)

**Comment by geneishouko** [comment]
@MysticMole It looks like it's some trigger related code that is crashing but unfortunately that isn't my expertise. Try a more recent release and if it still crashes please tell what modules are in use in your class. If a class with different characters still makes the game crash.

**Comment by geneishouko** [comment]
@SaotomeRanma142 It possibly is character related. Try a class with different characters, maybe the illusion provided cards.

**Comment by SaotomeRanma142** [comment]
> @SaotomeRanma142 It possibly is character related. Try a class with different characters, maybe the illusion provided cards.

I was supecting this. Currently testing with vanilla characters. No crashes so far, but it can take quite some time for crashes to happen. Next I will start adding modules a few at a time and see which ones if any cause the game to crash.

**Comment by linkanon** [comment]
If it's indeed modules then make sure you're up-to-date first. Latest modules are here: https://pastebin.com/R4DW0dxw
If these crash too then it could be one of the broken ones and we possibly already fixed it so I suggest either dropping by the discord or finding the problematic one yourself and we'll post the fixed version.
