### ISSUE TITLE
Suggestions for AAU

### ISSUE THREAD

**Issue by Aa8man** [aa2g/AA2Unlimited#134]
1. Blush Fix in H-Scene
Blush option will be ignored and disappeared when the facial expression in-game changes. Same goes for Mouth, Eyes, Eyebrows option. Maybe there could be check box for 'lock' this options, or make it default to fix this options not to be changed in-game.

2. Strap-on bones fix
If you want this bones to be adjusted,  you should add 'props skeleton'. 
The critical issue is, Strap-on bones often don't follow the character's bone(the hip). It should be fixed.
And making it default to be adjustable(without props skeleton) would be good. Why not?

3. Animation for added char in H-Scene
Adding char to H-Scene is very good function and my favorite, while loading animation is also AAU's one of the good function. But load XA won't work for added char at all. 
It would be great to use in H-Scene, make AA more variety of H-Scene in general. (Adding char at H-Scene is cool, but they just stand there like stone!)

4. Enhanced CharProps
Adding tab of 'CharProps' at Bones/Clothes/Light position. It works like props, but it also works with bones. Currently CharProps should be set in file to work properly as 'CharProps', but this tab makes available to any props to work like CharProps, by binding props into specific bones to character. 
So it has option to select char and char's bone to bind with, and other slider to rotate, scale, and translate, and it would follow the bone's movement.

5. Save/Load for light
Newly added light is good, while you should set the value of light every time you turn on.
Save/Load just like Poses and Scenes would be good.

**Comment by linkanon** [comment]
1. to my knowledge it's not doable
1. it's in the plans whenever we figure out how to actually do it
1. you can load .xa on any actor in the scene just fine. You just have to select it
1. it's in the plans whenever we figure out how to actually do it
1. doable but should be separate from the scenes and poses themselves

**Comment by Aa8man** [comment]
3. To me load XA for added char doesn't work at all. the char changes scale, but animation don't be applied at all. 
And load XA in lesbian sex, it won't work, too. load xa to leading char and animation malfunctions.
