### ISSUE TITLE
Feature request: Outlines/Shadow for subtitles

### ISSUE THREAD

**Issue by Tyrn-11** [aa2g/AA2Unlimited#136]
The old subtitle overlay from the HF patch had the option for the displayed text to have an outline and a shadow. These were black by default and, together with the white text, helped immensely with keeping the text readable on bright backgrounds.

Could similar settings be integrated into the recently added subtitles feature?

**Comment by kayfour** [comment]
We have revamped the subtitles to have settable colors and outlines!
