### ISSUE TITLE
Visual Studio 2015 Compile: libzstd_static.dll 

### ISSUE THREAD

**Issue by BenCat07** [aa2g/AA2Unlimited#143]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'libzstd_static.lib'	AAUnlimitedDll	C:\Users\0\AA2Unlimited\AAUnlimited\LINK	1	

I get this error on compile, All the dependenvoes listed are installed, i am using Windows 10 with Visual Studio 2015, i Tried building all but pp2 on win32 in release/Debug mode (no difference), i'd appreciate if someone could tell me what i am missing here or what i should do to fix this issue. Thanks.

**Comment by geneishouko** [comment]
Pull all the git submodules and read 3rdparty/README.md

**Comment by BenCat07** [comment]
this is so sad why does Visual Studio do this

**Comment by kayfour** [comment]
it hates you

**Comment by BenCat07** [comment]
for zstd do i select Upgrade or do i leave it be at VS2010?

**Comment by geneishouko** [comment]
Upgrade

**Comment by BenCat07** [comment]
Alright, thanks for the help, all worked
