### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by MasterCraftsman2** [aa2g/AA2Unlimited#144]
So I've done the process exactly as instructed but once I get to the launcher and actually try to launch the game, I get "unhandled exception" I really need help.

![image](https://user-images.githubusercontent.com/48257945/53828127-6700ae00-3f42-11e9-929d-cbf63aab9efa.png)

**Comment by kayfour** [comment]
Do you have nvidia? If so, try [this entry](https://github.com/aa2g/AA2Unlimited/wiki#i-have-nvidia-crashes-or-glitches-help) from the FAQ.

**Comment by MasterCraftsman2** [comment]
Thanks, this really helped
