### ISSUE TITLE
Some additional settings in config.lua

### ISSUE THREAD

**Issue by Mirgosoft** [aa2g/AA2Unlimited#147]
In the beginning I want to thank the author for the wonderful work on this mod. Now play much more interesting and more enjoyable than in the simple version of the game.
However, for me, as well as for my friends, some settings are very necessary for a more convenient game.

1) For POV mode:
(At the start by pressing "A" key)
- Starting position X, Y and Z (​​positive or negative values)
- Starting FOV value (after exiting the POV mode, the FOV value is returned to the previous value)
- The sensitivity of the mouse in the POV mode. It is too high now.
Also, a nice addition will be the ability to set the key of activation/deactivation mode on the additional mouse buttons (but this is not necessary)

2) For Subtitles:
- Position (X, Y) and the size (width and height) of the subtitles area (RECT rect = { 0, 40, 1024, 256 };).
- Text Color (R, G, B).
- Align text inside the area. (not necessary)
- The color and thickness of the outline or parameters for the text shadow (Can be difficult to implement, so it is not necessary)

3) I also want to know how to find these addresses (offsets) in AA2Play.exe?

[0xDBE64] = "Track",
[0xF4DE4] = "Track",
[0xF4E21] = "Swimming",
[0xDBF06] = "Swimming",
[0xF4E52] = "Baseball",
[0xDBFA6] = "Baseball",
[0xF4E94] = "Volley",
[0xDC04C] = "Volley",
[0xF4ECD] = "Dojo",
[0xDC0F2] = "Dojo",
[0xF4EE5] = "Fine arts",
[0xDC198] = "Fine arts",
[0xF4F27] = "Culture",
[0xDC23C] = "Culture",
[0xF4F47] = "Other",
[0xDC2EA] = "Other",

For our custom Russian launcher with Tahoma font fix, half of them (Dojo, Fine arts, Culture, Other) are not working now.

4) The values in the "playtrans.lua" file, specified in Russian, are displayed in the game with spaces: “К л у б  А т л е т и к и” (font problem - Tahoma font is required)

I understand, I beg a lot, and I apologize. Hope for understanding.

**Comment by geneishouko** [comment]
Q 1. and 2.
Thank you for your suggestions. These may be implemented in a future release of AAUnlimited.

Q 3. and 4. You add 0x400000 to the pointer to get the offset to the string pointer. May I ask if you are translating playtrans.lua to Russian and if you aren't, why not?

**Comment by Mirgosoft** [comment]
Q 3: I solved the problem by simply modifying AA2Play.exe by myself for the Russian language.

However, one problem remained with AA2Unlimited mod.

Q 4: Please, look at this image for a better understanding. [image](https://imgur.com/gWpQlp6)
I translated everything that is needed. But the problem with cyrillic letter-spacings remained only in one place. Without AA2Unlimited mod, this problem is not observed in all repacks. Therefore, the problem is certainly in AA2Unlimited. Can be fixed by using 'Tahoma' font.

**Comment by geneishouko** [comment]
Q 4: That problem is probably locale related. Do you have fixlocale enabled or disabled? Try the opposite of it.

**Comment by Mirgosoft** [comment]
Turned on and off fixlocale - No effect.
And in the source code I can not find a place where I can change the font for this place.
