### ISSUE TITLE
Can't install the patch

### ISSUE THREAD

**Issue by afnix** [aa2g/AA2Unlimited#153]
![error](https://user-images.githubusercontent.com/49964780/56701057-51636580-66f5-11e9-8bcb-088bceecada4.png)
I'm using the alt_patcher.exe because the batch file wouldn't open.
Now I can't patch the aa2play.exe but the aa2editor.exe patched.

**Comment by linkanon** [comment]
Where did you get that `aa2play.exe`? It's confirmed to work with unmodified `aa2play.exe` and a handful of others.

**Comment by afnix** [comment]
I uninstalled the mods, now it works.
Thanks!
