### ISSUE TITLE
Problems with installing the patch

### ISSUE THREAD

**Issue by kryptomaniax** [aa2g/AA2Unlimited#157]
Hi, so whenever I try to put the patch in the game, it says that it's not the correct "aa2play/edit" file, and it says it's a failure. I have tried this in the past, it succeeded with the patch but it never actually worked (specifically with the editor, it loads up, but the screen is completely white and it doesn't work), and other times, it didn't even load the patch in, and whenever I tried opening it, an error popped up (which was completely in Japanese), if anyone can help me I'd appreciate it, I'm on windows 10

**Comment by Scout25DA** [comment]
> Hi, so whenever I try to put the patch in the game, it says that it's not the correct "aa2play/edit" file, and it says it's a failure. I have tried this in the past, it succeeded with the patch but it never actually worked (specifically with the editor, it loads up, but the screen is completely white and it doesn't work), and other times, it didn't even load the patch in, and whenever I tried opening it, an error popped up (which was completely in Japanese), if anyone can help me I'd appreciate it, I'm on windows 10

Please try to download the latest version of AA2Unlimited or try to reinstall AA2.
Second method... Try to change the regedit patch "HKEY_CURRENT_USER\Software\ILLUSION\AA2Edit" and change the value of "INSTALLDIR" of your folder.

**Comment by k4yf0ur** [comment]
Get [mini](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0).
