### ISSUE TITLE
Says it can't find c:\\Illusion\Artificial'   "WTF?"

### ISSUE THREAD

**Issue by sithlordslim** [aa2g/AA2Unlimited#158]
This is what happened when I tried to launch it after it patched and the AAUnlimited window was frozen there after. I made sure to take the snippet with the installation path with the files in folder as it was the only thing it would do, but either way I'll have to reinstall, no biggie. I've also included a logfile, I'm not sure if it's the games or yours, but hopefully it will help.
I did stop by the Discord channel place/thing and well, here I am, because it was dead over there, like no group nothing, like it doesn't exist.
Thank you though, if you can inform me on what I did wrong (maybe and highly likely, I'm just f'n stupid), or if there is a workaround or just a glitch in the matrix.
The batch file did patch the shortcuts, but this is what happened, I tried moving the contents of AAUnlimited into the the game install directory and that was worse as it couldn't find it's dll files, so I don't know what to do.
[logfile.txt](https://github.com/aa2g/AA2Unlimited/files/3190338/logfile.txt)

![The Error I get](https://user-images.githubusercontent.com/29677395/57910413-18bd3480-783a-11e9-9892-3ce99446747a.PNG)

**Comment by FAINEENA** [comment]
How?
