### ISSUE TITLE
how to uninstall aa2unlimited?

### ISSUE THREAD

**Issue by delete47283** [aa2g/AA2Unlimited#159]
my c drive reinstalled
and my aa2 didn't work (aa2 is the other drive)
plz how to reinstall aaunlimited

**Comment by Scout25DA** [comment]
> my c drive reinstalled
> and my aa2 didn't work (aa2 is the other drive)
> plz how to reinstall aaunlimited
Well this is kinda complex to fix this... But hey try to copy your AA2 main game to the C Drive and then delete it by using install.bat (Uncheck "patch") and make sure you didn't launched AA2.

**Comment by k4yf0ur** [comment]
Sounds like a registry issue. Run the registry fixer which is a part of "aa2install".
