### ISSUE TITLE
Infirmary Wild trait invitation Sex Crash

### ISSUE THREAD

**Issue by Xytes** [aa2g/AA2Unlimited#168]
https://mega.nz/#!3wwHXYIb!3D3YimXW7UuySnoj6PwfUCOUbyUsNkCgzvJDYnbGfIQ

This happens around 60% of the times, when any wild character with modules ( i didn't try it without them) invites me to skip class and have sex in the infirmary.
I noticed that when the game crashes the dialog before the sex is the same as the one that you see when you skip normally and not the alternative one linked at the infirmary-sex event.

**Comment by Scout25DA** [comment]
> https://mega.nz/#!3wwHXYIb!3D3YimXW7UuySnoj6PwfUCOUbyUsNkCgzvJDYnbGfIQ
> 
> This happens around 60% of the times, when any wild character with modules ( i didn't try it without them) invites me to skip class and have sex in the infirmary.
> I noticed that when the game crashes the dialog before the sex is the same as the one that you see when you skip normally and not the alternative one linked at the infirmary-sex event.
Try these methods
1. Try to update AAUnlimited to latest
2. Reinstall AA2
3. Delete More H Positions and Replace them with your backup files.

**Comment by kayfour** [comment]
The infirmary sex crash is a known issue and will be resolved in the next AAUnlimited release. There is no need to try anything else other than updating your AAU once the new version of it is released.

**Comment by Xytes** [comment]
Thank you for your replyes, i will update AAUnlimited as soon as i can(and follow the suggestion by Scout25DA) or i will wait for the next update.
I opened this issue because i wanted to notify the developement team abot this bug and offer my point of wiev and i'm happy that it was already noted.
Thank you for your hard work and your support !
