### ISSUE TITLE
crash, aa2mini

### ISSUE THREAD

**Issue by xHexanna** [aa2g/AA2Unlimited#177]
because i use mini im not sure where to find aaunlimited.dll and such. But this crash is happening a lot and I'm getting really annoyed. I'm not good with programming so i have no idea what to do or how to fix this.

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/3484389/aaucrash.zip)

**Comment by alex20114349** [comment]
To find the other files besides the crash dump in the AA2Mini root folder, where the exe is, you can search for it using the search function in the top right of explorer. Searching for the file name should find both files.
