### ISSUE TITLE
aau error! can't run aa2

### ISSUE THREAD

**Issue by dish2** [aa2g/AA2Unlimited#181]
...Unlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\dlgmod.lua:58: attempt to index a nil value (local 'm')
stack traceback:
	...Unlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\dlgmod.lua:58: in method 'toggle'
	...nlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\dlglist.lua:96: in function <...nlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\dlglist.lua:94>
	(...tail calls...)
	[C]: in function 'iuplua.MainLoop'
	...\AAUnlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\dlg.lua:478: in function 'launcher.dlg'
	...AAUnlimited_v1.5.3 (1)\AAUnlimited\mod\launcher\init.lua:26: in function 'launcher.load'
	[C]: in function 'xpcall'
	...s\CS\Desktop\AAUnlimited_v1.5.3 (1)\AAUnlimited\init.lua:359: in function 'init_module'
	...s\CS\Desktop\AAUnlimited_v1.5.3 (1)\AAUnlimited\init.lua:396: in function 'init_modules'

**Comment by dish2** [comment]
enable win10fix, Occur this error.

**Comment by k4yf0ur** [comment]
Try following this [guide ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0) and see if it fixes your issue.
