### ISSUE TITLE
0x75A0845D

### ISSUE THREAD

**Issue by mrlurker1994** [aa2g/AA2Unlimited#186]
Good day everyone.
I have a problem with the game.
The game crashes every time.
I don't know what happens, if you could explain to me how to avoid that I would be grateful
PS: the problem comes out every so often, here I leave the aaucrash.dmp along with the rest of the things: 
[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/3833942/aaucrash.zip)

I hope someone can help me please.

(I'm sorry for my English)

**Comment by k4yf0ur** [comment]
The crash is related to your pp2 cache settings. Try these settings instead.
![settings](https://user-images.githubusercontent.com/35668308/84168340-95d7cf00-aa77-11ea-8f35-df2d2ffb3e3c.PNG)
