### ISSUE TITLE
rdata.size 0x6164722e error

### ISSUE THREAD

**Issue by Iklonar** [aa2g/AA2Unlimited#187]
When trying to install this, I'm told that my AA2Play has an rdata.size of 0x6164722e while the program "expected around 0x71482". This is using the 4th DLC pack (the one that has a new .exe); any previous AA2Play has an rdata.size of 0x0. Which AA2Play has 0x71482? As far as I can tell, I'm being asked for a file that does not exist.

**Comment by Iklonar** [comment]
Tried a new installation method and fixed it.

**Comment by hidorii** [comment]
I'm having the same issue, could you tell me the new installation method you used to fix it? :')
