### ISSUE TITLE
Crashes 100% of the time whenever someone speaks

### ISSUE THREAD

**Issue by Jwguy** [aa2g/AA2Unlimited#190]
I'm experiencing an issue where the game crashes as soon as anyone speaks. I've not had a successful game since installing AAU. Any ideas?

![Capture](https://user-images.githubusercontent.com/16468732/69849196-a645fc00-1241-11ea-9e70-9adc4d51f27b.JPG)

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/3904030/aaucrash.zip)

**Comment by mrlurker1994** [comment]
Wait for someone to answer you here.
Go to this discord channel if anyone knows how to fix that problem.

https://discordapp.com/channels/306103444333264896/313793357010829314

Sorry for not being able to help you with this.

**Comment by k4yf0ur** [comment]
You did not file a proper [crash report](https://github.com/aa2g/AA2Unlimited/wiki/How-To-Report-a-Crash). 
In the meantime, try following [this guid ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0) to get the game up and running.
