### ISSUE TITLE
Crash when using AA2Mini, also happens when using the original installed version

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#193]
The game has a random crash when running AAUnlimited, this happens whether in school or in your room. I did have this happen once while it was randomizing the class on day one, but it mostly happens in the first two time periods in school.

[Crash.zip](https://github.com/aa2g/AA2Unlimited/files/4005192/Crash.zip)

**Comment by alex20114349** [comment]
Tested for module issues after reporting, still crashing. Also tested the Win10 fix possibility and found out something interesting, it crashes immediately on hitting the start button at the bottom of the AAU launcher if using the WineD3D option, this crash is consistent and happens every time. The only fix I can find for that is using Win10Fix.

**Comment by k4yf0ur** [comment]
Hey, I looked at the crash dump and I'm not quite sure what's causing the issue, so we'll need to get some more information. Next few times this happens, upload the crash dumps here as well, as many as you can. 
Also, it appears that the issue is being caused by a female card. So if you have a class in which you are consistently getting this crash, try removing all of the female cards temporarily to see if it fixes the issue. If it does, start removing the cards one by one to see if you can isolate any specific card that causes it.

**Comment by alex20114349** [comment]
First pass complete, 1 card out of 20,000 threw a crash error as I described, in the 0x00000 format, as soon as I tried to edit the uniform to be used while on that save. Doing a second pass now where I will incorporate your suggestion of doing one full class each and test each individually to see if I can get into the uniform editor. Is there a way to save the card throwing the error like editing it again to try and flush out the bad data?

**Comment by alex20114349** [comment]
Some of the cards that were cleared the first time seem to be crashing on randomization, switching to singling out cards until I can randomize successfully. The last card removed from the active folder is the culprit.

**Comment by alex20114349** [comment]
Second pass complete, I have confirmed errors on loading into a class and errors on entering uniform edit mode were caused by three specific cards, however, I am still testing for the random crashes during school periods. This pass is going to take a while due to the inability to identify what card, if any, causes the crahses unless I remove each card individually. Once again, looking for what point the crashes stop, the last card removed being the cause if any are causing it at all.

**Comment by linkanon** [comment]
random crashes in the class aren't usually caused by cards
if a card crashes consistently when you add it it's usually either due to faulty overrides or you not having a mod the card tries to use(e.g. people who make guys trying to override ikemen faces while you don't have the underlying mod. They apply the face morph but forget to include the tongue which you need installed otherwise it crashes)
try confirming that those cards crash consistently and then try nuking all their overrides and see if they work. If they work you can isolate the overrides that cause problems. 
also
>20000 cards
damn son you don't need that many

**Comment by alex20114349** [comment]
I can already answer as to the consistency of the crash, it is very random, maybe during the opening period, maybe the second, maybe the third. At first, I thought it had something to do with something out of date resulting in a bug that had been fixed in the latest version of that mod. I was wrong, I updated it and still got crashes. It mainly happens in the second and third time periods, but can happen in any. I could be doing anything with anyone, the only consistency to this is that it never happens while under any kind of pause, so it is being triggered by something happening in game.

**Comment by alex20114349** [comment]
Got a crash while switching periods between second and third after the fade to black.

**Comment by k4yf0ur** [comment]
Pressing the button to randomize a class can cause crashes on windows 10, as well as any other interaction with the roster really. That crash dump is less informative than the first one.
Post a couple more crash dumps when you get the chance, just so we can see whether they will happen in the same place or not. Also, update your [modules](https://pastebin.com/R4DW0dxw).

**Comment by alex20114349** [comment]
> 
> 
> Pressing the button to randomize a class can cause crashes on windows 10, as well as any other interaction with the roster really. That crash dump is less informative than the first one.
> Post a couple more crash dumps when you get the chance, just so we can see whether they will happen in the same place or not. Also, update your [modules](https://pastebin.com/R4DW0dxw).

Well, I'm not getting crashes there, anymore, but I did get one while just standing in the Old Building 1F. These are in the same format, the 0x00000 type message that can only be interacted with by keyboard, but they appear while at school while doing anything. I think there's a rogue card still around as the crashes seem to happen pretty often with a few potential culprits that get randomized into the class more than most. The thing that's making this hard is that I can't tell who it is, but I think it might be an interaction between two NPCs with one or both being bad cards in terms of AAU. Also, the latest of these crashes started a consistent crash in the same format on loading the save where it would crash the second I hit load. This consistent crash did not happen before it crashed at school the last time while standing alone in Old Building 1F.
[crash.zip](https://github.com/aa2g/AA2Unlimited/files/4808762/crash.zip)

**Comment by alex20114349** [comment]
Another crash in school, unknown culprit as the one I suspected in the previous in school crash was not in this class. It was the same format, but did not lock me out of the save with a consistent crash after the initial crash.
[crash.zip](https://github.com/aa2g/AA2Unlimited/files/4874925/crash.zip)

**Comment by NightlyCanary** [comment]
I got a crash when loading one of my save files. Can anyone help me figure out the problem?

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/4977279/aaucrash.zip)
