### ISSUE TITLE
Crashes in the infirmary

### ISSUE THREAD

**Issue by DazzleHassle** [aa2g/AA2Unlimited#197]
Looked at the recent notes, said the crash in the infirmary was gone but it takes place for me still. So far it only crashes when someone invites me to skip class and snooze about in that darn room. Any way to resolve this?
Didn't save the crash notes I'm afraid but I can always rig it all up to make it happen again if the crash report is desired.
Love some help on this matter.

**Comment by Nuxf9** [comment]
same here

**Comment by k4yf0ur** [comment]
The issue will be fixed in the next release, sorry for the inconvenience.
