### ISSUE TITLE
other face are not working 

### ISSUE THREAD

**Issue by grant-24** [aa2g/AA2Unlimited#199]
i dont know what to do please help me
![2020_0107_1443_20587](https://user-images.githubusercontent.com/59596196/71874145-1fe3da80-315c-11ea-838f-cdb16877c43f.png)

**Comment by k4yf0ur** [comment]
You are missing the assets for those other faces. AAU unlocks the options of adding those faces, but other mods are needed to fill those slots. Consider following [this ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0) guide.
