### ISSUE TITLE
game always crashes at start of H scene

### ISSUE THREAD

**Issue by SaotomeRanma142** [aa2g/AA2Unlimited#206]
game always crashes at start of H scene. Turning off triggers & modules or setting AA2 to skip the H scene will avoid the crash.
[Crash.zip](https://github.com/aa2g/AA2Unlimited/files/4303750/Crash.zip)

**Comment by linkanon** [comment]
what modules/triggers do you have in your class?

**Comment by SaotomeRanma142** [comment]
There are many modules. Attached is JSON file from the class.
[Makermay学園1年1組.txt](https://github.com/aa2g/AA2Unlimited/files/4303753/Makermay.1.1.txt)

**Comment by linkanon** [comment]
There's quite a few unknown/unofficial modules here. I believe DK and FK stand for `Dark Knight` and `Force Knight` respectively.
Most likely one of the cards has triggers that mess it up for everyone. I suggest taking out one card at a time to see which one is causing it.

**Comment by SaotomeRanma142** [comment]
I think I got it. Suspecting the "futanari" module. Took out character #11 which had futanari and ambusher modules installed. No crash. Will do further testing on the remainder of the class and if no further crashes will consider this solved.

**Comment by linkanon** [comment]
In addition to that check if your AAU is up to date and that you have homosex enabled in the `unlocks` script's settings

**Comment by SaotomeRanma142** [comment]
Made sure I am running latest AAU and that the homosex option is enabled in the unlock script settings, the futanari module still causes the crash.

**Comment by kayfour** [comment]
What is the gender of your player character? Who is initiating the sex?

**Comment by SaotomeRanma142** [comment]
Found the problem. The character causing the crashes had a trigger on her that was not part of a module. Removed it and all crashes stopped.
