### ISSUE TITLE
Patch Failed

### ISSUE THREAD

**Issue by newky131** [aa2g/AA2Unlimited#207]
i can't install AA2Unlimited 
![image](https://user-images.githubusercontent.com/62044904/76379323-5f0ff100-6382-11ea-868e-01e127c5928a.png)

**Comment by k4yf0ur** [comment]
Run the patcher as an administrator. 
Alternatively, follow [this ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0 )guide to not have to patch the files manually.
