### ISSUE TITLE
Unhandled exception: 0xC0000005/ 0x004C4E8E

### ISSUE THREAD

**Issue by throwaway123456789101112** [aa2g/AA2Unlimited#210]
Have a bit of a problem and would greatly appreciate some support on this. AA2 continuously crashes after a few NPC conversations occur and I'm unable to find anything concrete on both the guide or anywhere else for that matter. I have already tried disabling modules but that did nothing.

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/4470032/aaucrash.zip)

**Comment by k4yf0ur** [comment]
You did not follow the proper crash [reporting procedure.](https://github.com/aa2g/AA2Unlimited/wiki/How-To-Report-a-Crash) 
For now, attempt following the modern installation [guide ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0 )and see if that fixes your issue.
