### ISSUE TITLE
rdata error

### ISSUE THREAD

**Issue by GreenNBlacko** [aa2g/AA2Unlimited#211]
![image](https://user-images.githubusercontent.com/45263750/79644139-a7a3a100-81af-11ea-848f-8a4817aa174a.png)
![image](https://user-images.githubusercontent.com/45263750/79644231-3b756d00-81b0-11ea-9502-050f14617466.png)
I have a clean install of aa2 edit and aa2 play, so it _should_ be original, right?
does this mean that the installer can't access the files?

**Comment by linkanon** [comment]
your game should also have all the official patches and DLC installed

**Comment by GreenNBlacko** [comment]
so english patch and append sets?

**Comment by linkanon** [comment]
no, the game had 12 official patches. You require those
check [/aa2g/](http://boards.4channel.org/vg/aa2g), they have guides and everything you need for this game

**Comment by k4yf0ur** [comment]
Follow the modern AA2 installation [guide](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0).
