### ISSUE TITLE
Can't find AA2Play error when attempting to launch AA2Edit or AA2Play

### ISSUE THREAD

**Issue by aradinfinity** [aa2g/AA2Unlimited#212]
I pointed the installer to the files, and it gave me messages that indicated it had successfully done its thing; however, when I try to launch them I get "Critical Error: Could not find AAPlay path in registry." I'm on a Windows 10 machine and have left the installer in my Downloads folder, with the exe files I pointed it to in the Program Files folder. I've tried running the installer as admin (it thought it was missing a dll that was right there in the same folder) and renaming AA2Play to AAPlay, then pointing it there. What am I missing?

**Comment by k4yf0ur** [comment]
Follow the modern AA2 installation [guide](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0).
