### ISSUE TITLE
Futanari Module crashing AAU

### ISSUE THREAD

**Issue by AnonHarlot** [aa2g/AA2Unlimited#213]
Every time I try to add the Futanari module to a character, I get this specific error:
![UNHANDLED EXCEPTION](https://user-images.githubusercontent.com/66073664/83149079-53011900-a0bf-11ea-9ed5-4cb33824554f.PNG)

Here's a screenshot of the Memory Dump File that I get:
![DUMP SUMMARY](https://user-images.githubusercontent.com/66073664/83149427-aa06ee00-a0bf-11ea-873a-5332f58b9ad8.PNG)

Now, I'm a fool, so if anyone could tell me what this means and how to fix it, that'd be great. I just don't know if its a problem on _my_ end, or a problem with _AAU_

**Comment by k4yf0ur** [comment]
[Update ](https://github.com/aa2g/AA2Unlimited/wiki/Installation#updating )your AAUnlimited and try again

**Comment by AnonHarlot** [comment]
I had two folders of AAU and didn't notice I was using the other folder, nvm lol
