### ISSUE TITLE
Crashing when starting a conversation

### ISSUE THREAD

**Issue by unnamedmangoman** [aa2g/AA2Unlimited#214]
Doesn't happen immediately but after a few minutes, starting a conversation causes a crash

tried a save with triggers/modules turned off but still crashes

[crash.zip](https://github.com/aa2g/AA2Unlimited/files/4748137/crash.zip)

**Comment by k4yf0ur** [comment]
The last few times people have reported this issue, they had a problem with their pp2 settings. Are you running AA2Mini? In case you aren't, follow [this ](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0) guide to ensure that you do. You'll get higher FPS, the game will be more stable, as well as 90% more compact. Once installing AA2Mini, test to see if your issue persists.

**Comment by unnamedmangoman** [comment]
yes i am running aa2mini and still crashes, tried all possible combinations of win10fix, wined3d, software vertex processing. I'll look into the pp2 settings and see what i can do

**Comment by k4yf0ur** [comment]
Try these settings if you don't have them already 
![setting](https://user-images.githubusercontent.com/35668308/84177629-64fd9700-aa83-11ea-83ae-0241ea5129e8.PNG).
Also, in scripts tab, under win10fix settings you can choose dgvoodoo2 option. Try that with every combination as well.

**Comment by unnamedmangoman** [comment]
[crash2.zip](https://github.com/aa2g/AA2Unlimited/files/4753817/crash2.zip)

yeah i'm still getting crashes :(
