### ISSUE TITLE
H-Scenes subtitles

### ISSUE THREAD

**Issue by Kazumin1994** [aa2g/AA2Unlimited#215]
I'm doing an "amateur" translation for Brazilian Portuguese, but I can't find the LST/TXT files of the H-Scene subtitles, among the LST files extracted from pp2 using the "cruft" method, i've searched all of the files, one by one, all the dialogue are there, for all 25 personalities, even the menu ones, every single little thing has been found and translated, but i can't find the damn H-Scene subtitle lines, i even used programs like PowerGREP 5 to search among all files for quotes i saw the girls saying in the actual game, but no success at all, i don't know if this is the right place to ask for help, or if someone will answer that (Rip HongFire), thanks anyway...

**Comment by linkanon** [comment]
the game doesn't have subtitles for H lines

**Comment by Kazumin1994** [comment]
> the game doesn't have subtitles for H lines

![2020_0407_2235_52383](https://user-images.githubusercontent.com/66762426/84341239-031f5900-ab79-11ea-8e74-8befccf43b3a.png)

What is this then?

**Comment by Kazumin1994** [comment]
> the game doesn't have subtitles for H lines

https://imgur.com/a/dKH1YPP
What is this them?

**Comment by linkanon** [comment]
one fat ass
AAU includes a mod for subtitles, they're not part of the game itself. I believe you're looking for the `AAUnlimited\subtitles.txt`

**Comment by Kazumin1994** [comment]
> one fat ass
> AAU includes a mod for subtitles, they're not part of the game itself. I believe you're looking for the `AAUnlimited\subtitles.txt`

Oook, its settled, I'm dumb as fuck... Thank you so much, i'm searching for this since 12 AM *_*
