### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by JesusChristGodDamn** [aa2g/AA2Unlimited#216]
Hello, the game crashes at random times, that's really all i can say. Does anyone have a solution for this?

Code: 0xC0000005
Address: 0x0144E86A

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/4767860/aaucrash.zip)

**Comment by k4yf0ur** [comment]
The crash dump isn't informative enough to tell, but I can see you aren't using [AA2Mini](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0). Consider installing it and seeing if you still get crashes on it. That way we'll know whether it was a mod conflict issue of some sort or not.

**Comment by JesusChristGodDamn** [comment]
Nope, installed AA2Mini, still getting crashes. i guess it's a mod conflict then?

**Comment by k4yf0ur** [comment]
That means it's not a mod conflict. If you're running windows 10, check [this](https://github.com/aa2g/AA2Unlimited/wiki#im-trying-to-play-this-game-on-windows-10-and-im-getting-really-low-fpsthe-game-doesnt-work-what-do) out. Also, update your [modules](https://pastebin.com/R4DW0dxw).

**Comment by JesusChristGodDamn** [comment]
Modules are updated, i'm not on windows 10. Is there anything else i can try?

**Comment by k4yf0ur** [comment]
What's your operating system? When exactly are your crashes happening? Give me as many examples as you can, and post more crash dumps. Also, have you tried playing with a class of vanilla cards, to see if your issues persist?

**Comment by JesusChristGodDamn** [comment]
I'm on windows 8. The crashes happen randomly, however, i've noticed that they mostly happen during an H scene. Also, for example, i could be playing normally for like three days in-game, and on the fourth day it crashes. Or it just happens on the first day, no rules.

I have played with vanilla cards, there were no crashes. I think it's definitely got something to do with the modded cards.

Also, quick question, since i have AA2Mini, can i delete the vanilla install of the game that i have? Or do i have to have both AA2Mini and the vanilla install? Sorry if it's a dumb question, it's my first time using AA2Mini.

[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/4819639/aaucrash.zip)

**Comment by k4yf0ur** [comment]
You can delete the vanilla install of the game.

**Comment by JesusChristGodDamn** [comment]
Do you have anything else i can try?
Sorry for the late reply

**Comment by k4yf0ur** [comment]
Post a screenshot of the class that you are having crashes in. The game isn't crashing when you play with a vanilla class, so try removing the modded cards in your class one by one and see when the issue stops. Once it stops, try reloading into that save file and remove only the card whose removal caused the issue to stop previously, and see if there's no issues.
Also try a new class of modcards that doesn't include any of the cards in your current class.
