### ISSUE TITLE
Code: 0xE06D7363  Address: 0x760D4662

### ISSUE THREAD

**Issue by Matkip** [aa2g/AA2Unlimited#248]
First of all, I'm not a native speaker. I'm from Argentina, so, sorry if my English it's not that great.

Every time that i open AA2U everything seems fine, I open my save, and when I "go to sleep" everything starts to go very wrong. First, the menu, those icons that only apper when you leave the house, are there (i mean, they shouldn't, I think is like a bug), and finally whatever I do, click and icon, or if I leave it, appers the crash. Here're some pics that I take, if it helps.
![20201103_205057 1](https://user-images.githubusercontent.com/73916385/98053155-b3d31100-1e16-11eb-8033-b8b42b7ab21e.jpg)
![20201103_205118 1](https://user-images.githubusercontent.com/73916385/98053259-e54bdc80-1e16-11eb-90b6-8c7e1e4b38d1.jpg)
Here's the Dump File:
[Crash Dump.zip](https://github.com/aa2g/AA2Unlimited/files/5484749/Crash.Dump.zip)

All those thing that I mentioned just happen with AA2U, without AA2U it doesn't happen, just, works fine, as it should. But I really like AA2U, so if you can help me, I'll be very grateful. In any case, thanks for reading.

**Comment by linkanon** [comment]
This is the first time I'm seeing this bug so I can't provide any clear solutions.
It could be unrelated but I see that you're using the frontier launchers. It may work in some cases but generally nobody tests how AAU works with them. Depending on how modded your game is and how proficient you are I suggest either moving to an AA2Mini install or to a fresh normal install. In both cases set up the base game and test if it works with AAU and then add one mod at a time to see if it works.

**Comment by Matkip** [comment]
Well, I forgot to mention a few things that maybe could help, or maybe do the opposite.
One of my first problem with this game was the "invisible characters". I could fix it, but it's important to mention cause on of the solutions that I tried was this one: "SBAppLocale" with a ".bat" who executes the game, this thing gave me the exact same problem so I just deleted it.
So to resolve the "invisible characters" i found another solution, use the "LocaleEmulator", which didn't solution anything by itself, but yes if I change my "Region" in the Control Panel. Supposedly, AA2U doesn't need a LocaleEmulator, but for what've told, I guess, in my case, it's necessary cause, like I said, I can play it but just with "LocaleEmulator" and changing the Region every time that I want to play it.
So... yeah, in theory I can play it, but without the AAU. Maybe all that I said makes it worse but that's what I did 😢

(Sorry for my English)

**Comment by linkanon** [comment]
Yeah, looks like you had a long and thorny path. AAU indeed already includes a solution for the locale problems so you shouldn't use anything else. This game is very tricky to set up and most of the guides you can find on the internet are obsolete, wrong or both.
I suggest following [this guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub) to get a clean AA2.
If you follow it but the game still doesn't run properly you can visit our discord and someone might help you out.
(And don't worry about your English, it's more than intelligible)

**Comment by Matkip** [comment]
Thanks man, thanks for your patience and for your answers. Really, Idk what I did, but... out of blue now it's working, really, idk what've happened...
Anyway, thank you man.
