### ISSUE TITLE
Wiki link is broken

### ISSUE THREAD

**Issue by Nuxf9** [aa2g/AA2Unlimited#258]
The link for faceparts in Archive Overrides is broken. By the way there is any site for download mods? i only now this place.

**Comment by k4yf0ur** [comment]
http://tsukiyo.me/AAA/AA2MiniPPX.xml
http://www.mediafire.com/folder/vwrmdohus4vhh/Mods

**Comment by linkanon** [comment]
Updated the link, thanks for the heads up
