### ISSUE TITLE
Version 1.6 H Subtitles 

### ISSUE THREAD

**Issue by Kazumin1994** [aa2g/AA2Unlimited#268]
The other subtitles works fine, but the H scenes ones won't appear at all, i checked the script tab, the subtitle.txt is on the AA2MiniPPX\AAUnlimited\subtitles folder, i have v1.53 on another folder and it works fine, this v1.6 new subtitle update thing changed something, i can't figure what...
![V1 6 script](https://user-images.githubusercontent.com/66762426/100938635-cd2db280-34d3-11eb-80d3-983ff9c5dca4.png)

**Comment by linkanon** [comment]
This is a known issue. We'll be releasing a small fix soon-ish(about a week or two)

**Comment by Kazumin1994** [comment]
> This is a known issue. We'll be releasing a small fix soon-ish(about a week or two)

Thanks for the reply, V1.6 is really awesome, better graphics, better fps, better loading time,

**Comment by Ionize8** [comment]
Getting this issue on a new install that was immediately updated to 1.8
