### ISSUE TITLE
Picojson header missing

### ISSUE THREAD

**Issue by AA2Hackanon** [aa2g/AA2Unlimited#27]
looks like someone added some header file called picojson, but didn't actually add it to the repository. I found a version on github, that seems to work, but i'd prefer if the one that added it adds his version to the repository (versions n stuff).

**Comment by geneishouko** [comment]
Sorry about that. Git (or me) was silly and set a path with backslashes instead of forward slashes and it broke.

**Comment by geneishouko** [comment]
Oh. And to add it to the repository execute `git submodule update --init`

**Comment by linkanon** [comment]
Reopened so that it stays up until @AA2Hackanon sees it.
