### ISSUE TITLE
The game isn't opening at all 

### ISSUE THREAD

**Issue by wowpog** [aa2g/AA2Unlimited#279]
The game refuses to open on my end, I made sure I updated the vc86x/64x and it just won't open, same for the editor. I had ver. 1.53 and it worked fine so I think I might have updated it wrong I'm not sure...

**Comment by k4yf0ur** [comment]
You haven't really provided enough information for me to be able to help you. In the meantime, read this [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub).
