### ISSUE TITLE
Use .ppx resource loader, automatic lockup and crash upon hitting launch game.

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#290]
The title basically says it all, the 'use .ppx resource loader' option is currently broken. I attempted to toggle several different launcher options to figure it out, but that one alone stopped it from freezing up. Turning it off stops the freezing, but to test it further, I turned it back on and it began freezing again.

**Comment by b800047** [comment]
> It looks like the PPX server process (AAUnlimited\ppex\PPeXM64.exe) cannot start. Make sure that you have .NET Core — which you can find in the “extra” folder, or download it [here ](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer)— installed, and that you are running a 64 bit OS.
>If you have a 32 bit OS… The source code is available, so it should not take more than a minute to build a 32 bit version of it?
Found this post in another forum with a similar problem and worked for me...personally i prefer pp2 over ppx...

**Comment by k4yf0ur** [comment]
If you've installed ppx mini, don't try turning off the ppx resource loader or the game is simply not going to load the game files. Ensure that you've installed everything in the extra folder. Also make sure that the ppx process isn't already running, and if it is, kill the process. Once you've done that , reconfirm the issue and post screenshots of your data folder, and of your AAU launcher settings.

**Comment by alex20114349** [comment]
It seems to be killing itself just fine, screenshots attached.
![Untitled3](https://user-images.githubusercontent.com/59283313/117559612-d0196a00-b054-11eb-948d-9a0df7de40cc.png)
![Untitled2](https://user-images.githubusercontent.com/59283313/117559613-d0196a00-b054-11eb-85d4-3b8a3a056909.png)
![Untitled](https://user-images.githubusercontent.com/59283313/117559614-d0196a00-b054-11eb-9197-9b5c6a372161.png)

**Comment by alex20114349** [comment]
Forgot the data folder, my fault.
![Untitled5](https://user-images.githubusercontent.com/59283313/117561170-6c963900-b062-11eb-8e06-2fdb27c5785b.png)
![Untitled4](https://user-images.githubusercontent.com/59283313/117561171-6c963900-b062-11eb-82e6-e81af9341c70.png)

**Comment by k4yf0ur** [comment]
You can not use pp2 and ppx files at the same time. It doesn't work like that. Download mini and don't touch the configurations you aren't told to touch within the [guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub).
