### ISSUE TITLE
Windows 10: AAU launcher menu works fine until clicking "Launch", launcher hangs, never opens game

### ISSUE THREAD

**Issue by bethx** [aa2g/AA2Unlimited#293]
My title sorta sums it up, but I'll paraphrase it. I can open the launcher and edit the settings. When I press "Launch the Game", it starts to load and never stops, and the window for it says "Not Responding"- basically, it hangs.

Sorry if I'm being dumb and this falls under the Windows 10 crashing/low fps issues. I've followed that troubleshooting route and tried (I think) all of the combinations (the win10fix/wined3d variants, SVP/no SVP, Type 2 Renderer etc.) but to nothing has worked. I'm wondering if when you talk about those crashing issues, you mean that the game actually _starts_ and then crashes _and closes -_ or if that umbrella includes what I'm describing, where the game never opens but the launcher stays there, loading, "Not Responding".

So, if this is/could be a different problem, hopefully you can help me fix it! Oh, and is there a place I can get an up-to-date discord invite link? If that's somewhere I might be able to get help, I'd like to try there.

**Comment by Crazymanwerido** [comment]
I'm having the same problem with Windows 7, is there a command prompt window that opens for a split second when you try to run it? Because that's what's happening to me.

**Comment by b800047** [comment]
Is the "Use .ppx resource loader" box checked? Cause if you're using ppx files over pp2, you might need to install the .NET core file...

> It looks like the PPX server process (AAUnlimited\ppex\PPeXM64.exe) cannot start. Make sure that you have .NET Core — which you can find in the “extra” folder, or download it [here ](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer)— installed, and that you are running a 64 bit OS.
>If you have a 32 bit OS… The source code is available, so it should not take more than a minute to build a 32 bit version of it?

Found this post in another forum with a similar problem...to be honest .ppx and .pp2 are pretty much the same in terms of size and stability...

**Comment by tieme443** [comment]
I have the same problem and I verified it's the .ppx loader. I installed the .NET core file and the 2 redist files, but to no success. Am I missing something else or it just won't open?

This is the error in the log:
[ERROR] [bool __thiscall PPeX::Connect(const wchar_t *)]:

	       Failed to connect \\.\pipe\PPEX

**Comment by SilverLollipop** [comment]
> 
> I have the same problem and I verified it's the .ppx loader. I installed the .NET core file and the 2 redist files, but to no success. Am I missing something else or it just won't open?
> 

Was it the .NET Core v3.1? It think the installer wasn't included in the AA2MiniPPX if that's what you're using. This issue was reported here too and [the link included in this comment](https://github.com/aa2g/AA2Unlimited/issues/290#issuecomment-787587260) worked out for me. [Here's the link](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.10-windows-x64-installer) to the core download in that comment.

**Comment by k4yf0ur** [comment]
> > I have the same problem and I verified it's the .ppx loader. I installed the .NET core file and the 2 redist files, but to no success. Am I missing something else or it just won't open?
> 
> Was it the .NET Core v3.1? It think the installer wasn't included in the AA2MiniPPX if that's what you're using. This issue was reported here too and [the link included in this comment](https://github.com/aa2g/AA2Unlimited/issues/290#issuecomment-787587260) worked out for me. [Here's the link](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.10-windows-x64-installer) to the core download in that comment.
> 
> update: Ah. It only fixes the hanging issue, but "Failed to connect \.\pipe\PPEX" happens and they don't get loaded anyway.
> update2: Looks like I got the old AA2Mini, which didn't have the .NET Core included in extra. I don't know why, but the correct AA2MiniPPX package loads ppx files properly.

The extra folders of AA2Mini and AA2MiniPPX aren't the same. Ensure that you've installed everything in the extra folder of AA2MiniPPX if that's the one you're using.

**Comment by TheHexoctus** [comment]
It fixed my problem but I encountered a new problem where it shows a white screen, the menu music plays and everything just that it is stuck on a white screen
