### ISSUE TITLE
Installed properly for Edit but not Play.

### ISSUE THREAD

**Issue by BrossBean** [aa2g/AA2Unlimited#295]
So I see that other people have had this issue before but I still haven't been able to solve it using the solutions given to them, and there are people commenting with the same issue that have not gotten replies. When I used the install.bat it tells me "aa2play.exe doesn't appear to be AA2 play/edit exe file." because of the size mismatch yadda yadda. What gives? The solution says I need to get the original exe, but this should be the original exe. If it's not, where do I GET the original exe? Mine is right off the iso disk it should be the correct exe. I'm not using the English launcher or anything... I also tried the alt patcher. Still no luck. If someone could help me out, or maybe send me their exe or something? Please let me know.

**Comment by linkanon** [comment]
It requires all the patches and appends. Won't work with the vanilla 1.0 version of the .exe which is what you probably have. 
Check the [Installation](https://github.com/aa2g/AA2Unlimited/wiki/Installation) to see how to get your game running with the PPeX
