### ISSUE TITLE
Launcher not responding when launching mini.

### ISSUE THREAD

**Issue by BrossBean** [aa2g/AA2Unlimited#296]
I feel like a moron posting another issue within a few minutes of my last one being closed, but I decided to just get the pre-installed mini instead of figuring out my other issue. I got it all extracted and ready to go but the launcher freezes and says "not responding" when I try to launch. Does this for both play and edit no matter what settings I change. I'm not on Windows 10, I'm on Windows 8 (not 8.1). Troubleshooting in the modern AA2 guide document gives options for Windows 10 users if they encounter a crash and I even tried all of those and it's not working still.

**Comment by BrossBean** [comment]
If I can't figure this out I'll probably just join the discord listed at the bottom of the guide and ask there. I thank you in advance to any solutions you might be able to offer.

**Comment by HxxThSwggr** [comment]
Happens to me (win7) since the update to ppx. AA2Unlimited is not responding, but after a few minutes AA2 launches. Did you try waiting some time?

**Comment by BrossBean** [comment]
> Happens to me (win7) since the update to ppx. AA2Unlimited is not responding, but after a few minutes AA2 launches. Did you try waiting some time?

Waited an entire hour. Still nothing...

**Comment by BrossBean** [comment]
I found out the issue! The command prompt that pops up gave me an error message but it always went away too fast to read it! I took a video of it and slowed it down to read it. Turns out I'm missing a dll file. I was missing "hostfxr.dll" so I downloaded it. Then it told me I was missing Microsoft NETcore version 3.1.0 so I installed that and now it works!
