### ISSUE TITLE
Character Creator Crash

### ISSUE THREAD

**Issue by Pumabit** [aa2g/AA2Unlimited#297]
AA2 Edit always crashes when I save a character. 

Code: 0xc0000005
Address: 0x6B263697

**Comment by k4yf0ur** [comment]
Unfortunately this tells us nothing, so we can't help with your issue. Post screenshots of your data folder and AAU launcher settings, and read the page on [how to report a crash](https://github.com/aa2g/AA2Unlimited/wiki/How-To-Report-a-Crash).
