### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by StephanFS** [aa2g/AA2Unlimited#307]
Game and editor doesn't open, it only shows a white screen and nothing else. I've tried everything (including disabling .ppx resource loader), but nothing works.

**Comment by k4yf0ur** [comment]
Start posting screenshots of your data folder, and of your AAU launcher settings. Did you follow the ppx [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub)?

**Comment by StephanFS** [comment]
Tried everything from the FAQ. Every combination. It doesn't work, it just shows a white screen. So, I just lost everything because this piece of shit can't run on Windows 10, and I don't have 7 or 8 anymore.

Fuck this game. Fuck Illusion.

**Comment by k4yf0ur** [comment]
You want a pat on the back or tech support? In case of the latter, start posting what was asked of you.

**Comment by StephanFS** [comment]
> You want a pat on the back or tech support? In case of the latter, start posting what was asked of you.

I checked the game again. It seems it's related to the .ppx resource loader issue some users mentioned a few days ago. Tried to follow the instructions in the thread, but it didn't work.

Also it's a new installation. I didn't do anything with the launcher, just moved some cards (very old cards from before AA2Mini was a thing, they don't even use mods) and that's it.

**Comment by k4yf0ur** [comment]
Start posting screenshots of your data folder and AAU launcher settings.

**Comment by StephanFS** [comment]
> Start posting screenshots of your data folder and AAU launcher settings.

![2021-04-02 17_08_22-Window](https://user-images.githubusercontent.com/24442536/113450420-4a135f00-93d6-11eb-8595-d8bc3c9d3ea4.png)
![2021-04-02 17_08_35-Window](https://user-images.githubusercontent.com/24442536/113450427-4d0e4f80-93d6-11eb-8704-df922756f45b.png)
![2021-04-02 17_08_55-Window](https://user-images.githubusercontent.com/24442536/113450430-4f70a980-93d6-11eb-9d9f-0be32d1c9dfa.png)
![2021-04-02 17_09_05-Window](https://user-images.githubusercontent.com/24442536/113450432-513a6d00-93d6-11eb-8e37-729dc201a7da.png)
![2021-04-02 17_09_26-Window](https://user-images.githubusercontent.com/24442536/113450437-53043080-93d6-11eb-9d46-5b1a0073b0c3.png)
![2021-04-02 17_09_38-Window](https://user-images.githubusercontent.com/24442536/113450441-55668a80-93d6-11eb-9160-6e936a681593.png)

**Comment by k4yf0ur** [comment]
Why do you have a data folder inside of your data folder? That shouldn't be there. Aside from that, it looks alright. What windows 10 fix variant are you using? Post a screenshot of the white screen that shows up, and double check if everything from your extra folder is installed.

**Comment by StephanFS** [comment]
> Why do you have a data folder inside of your data folder? That shouldn't be there. Aside from that, it looks alright. What windows 10 fix variant are you using? Post a screenshot of the white screen that shows up, and double check if everything from your extra folder is installed.

Here's the thing: as I mentioned, if I run AAUnlimited with the "Use .ppx resource loader", it freezes when it launches. Only when I deselect it it starts to run, And here's the white screen:
![2021-04-02 17_17_57-Window](https://user-images.githubusercontent.com/24442536/113451068-94491000-93d7-11eb-8cf3-20d503b5d034.png)

I'm using AAEdit to make things easier. If I try to load a character, this happens:
![2021-04-02 17_20_07-Window](https://user-images.githubusercontent.com/24442536/113451130-b80c5600-93d7-11eb-9425-5c7f04708d7b.png)

**Comment by k4yf0ur** [comment]
Well, it's normal that the white screen is going to appear because you are disabling ppx resource loader while using ppx mini. You aren't loading the game files now. Re-enable it, and have the settings be just the same as in your screenshot. 
First of all, ensure that the ppex process isn't running already. Open task manager and if it is, kill it. Then open command prompt, navigate to the correct directory, and do this, and post a screenshot of the result. Give it some time to do its thing.
![ppex](https://user-images.githubusercontent.com/35668308/113451861-29153300-9403-11eb-8441-a47b6bba52b7.PNG)

**Comment by k4yf0ur** [comment]
Also, post a screenshot of the content of your extra folder in AA2MiniPPX

**Comment by StephanFS** [comment]
Now it runs.
![2021-04-02 17_48_17-Window](https://user-images.githubusercontent.com/24442536/113453066-a3ca5800-93db-11eb-9df8-58745daa4b06.png)

Also here's the extra folder
![2021-04-02 17_46_55-Window](https://user-images.githubusercontent.com/24442536/113453092-afb61a00-93db-11eb-8308-112662e7f122.png)
![2021-04-02 17_47_03-Window](https://user-images.githubusercontent.com/24442536/113453094-b2187400-93db-11eb-8169-cd37dad8ba83.png)

**Comment by StephanFS** [comment]
And ir crashes the moment I close the command prompt.

**Comment by k4yf0ur** [comment]
Well, it's normal for it to crash after you exit, but it's unusual that AAU can't seem to start ppex resource loader for you. Can you once again kill the ppx process and close aa2, and this time open aa2 normally, but give it a couple of minutes of being "frozen" to load up, and see what happens?

**Comment by StephanFS** [comment]
It worked. Didn't even need to kill PPX this time.

**Comment by k4yf0ur** [comment]
Good, have fun playing the game.

**Comment by Lyuoko** [comment]
> Well, it's normal that the white screen is going to appear because you are disabling ppx resource loader while using ppx mini. You aren't loading the game files now. Re-enable it, and have the settings be just the same as in your screenshot. First of all, ensure that the ppex process isn't running already. Open task manager and if it is, kill it. Then open command prompt, navigate to the correct directory, and do this, and post a screenshot of the result. Give it some time to do its thing. ![ppex](https://user-images.githubusercontent.com/35668308/113451861-29153300-9403-11eb-8441-a47b6bba52b7.PNG)

sorry, i am a bit dumb but, how did you do that? And my game folder was on disc D not C. Do i need to move it to C?
