### ISSUE TITLE
Polyamorus module not working.

### ISSUE THREAD

**Issue by BrossBean** [aa2g/AA2Unlimited#308]
So I have 3 students that I gave the poly trait. 1 girl and 2 guys. I wanted one of the guys to be dating the other 2 and let the 2 pairs in the group to be able to freely have sex.

However, the girl caught the 2 guys having sex, and now she has the red "Cheater!" speech bubble. I thought the poly module was supposed to make students immune to that sexual jealousy? Did I do something wrong? All 3 of them definitely have the module on them.

**Comment by k4yf0ur** [comment]
From what I can see, the module only removes the cheating status for the characters that are their lovers. But module issues aren't maintained through this github. Consult the [modclub](https://discord.gg/N37M9Ny) instead.
