### ISSUE TITLE
Yes sometimes registers as no and the reverse, no, I don't have a module meant to do this in play

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#311]
As the title says, I have an interaction, my lover confesses, I hit yes, she acts as if I said no when I was nowhere near the no button. On the opposite side, a girl who hates me because she became a victim to my PC equipped white knight module tries to Forced H me, I said no, it starts anyway. I do not have the wimp module equipped or anything else that would make denying her impossible.

In both cases, it acts as if I chose the opposite of what I actually chose. This could be game changing as, if the game registers a yes as a no for a confession, I lose love. On the other side, if the game registers a denial of forced H as accepting it and my lover sees, I have now cheated without even having any way to stop it. I might as well have been playing a lowest virtue character with the perverted and romantic traits with Auto PC active.

**Comment by linkanon** [comment]
![image](https://user-images.githubusercontent.com/13915973/117246782-3612b100-ae0b-11eb-9394-b23ab399b3ee.png)

**Comment by alex20114349** [comment]
I do not have this module at all. I've run some further testing and it looks like an issue with modules that increase the frequency of an action. These modules are not supposed to do that, but they are the only thing I can think of, especially when at least two of them went crazy on how high it set the frequency. I once had a girl offer eight massages in a row without even giving me time to move and then ask for four herself. She had the Masseuse module applied. I haven't had them offer a massage marathon since unequipping it on all NPC characters. I'm going to try unequipping modules that work on specific actions like studying is affected by Tutor. If my theory is correct and this stops the issue, the modules are bugged.

**Comment by alex20114349** [comment]
I've been testing and it does seem like the modules that increase freqquency, so not only are they set way too high on said frequency because the girl doesn't even give me a chance to move and sometimes goes into a marathon so long I'm forced to exit the game to stop it, but the modules seem to be bugged so that anything dealing with that action when requested by the girl is reversed on the yes/no prompt. Testing has revealed that girls who do not have, for example, the masseuse module will not offer massages as frequently, will not go into nearly endless loops of either requesting to be massaged or requesting to give me one, and will not have the options reversed. The same goes for the other actions. That said, when I applied the modules, I was using version 1.5.3 and the modules that were out at that time. It could very well be fixed in later versions.

**Comment by k4yf0ur** [comment]
Sometimes the game decides the character **has** to do something and until things change in the environment they will keep trying to do it. So if a module is overriding an action until something happens, that is the result. This is however another issue from the one you opened. Player's response being changed from yes to no, and from no to yes isn't on accident. Some modules will have that effect.

**Comment by alex20114349** [comment]
But not the ones I had at the time, this was on 1.5.3, when there were no modules with that effect. The repeated actions issue is different, but it is caused by the same modules that seem to also be reversing the options. I went through and unequipped every single one and haven't had a single multiple repetition marathon or a reversed option issue since.

**Comment by linkanon** [comment]
repeated actions and yes/no flip are different issues(if they are)

**Comment by alex20114349** [comment]
I'm well aware, but they are caused by the same thing, the modules that incease frequency of specific actions like the Masseuse, Tutor, and Coach modules. All three both increased the frequency of massage related actions, academic related actions, and athletic related actions and all three actions had the reverse yes/no prompt. According to my testing, both issues stopped on all three actions when I unequipped those modules. 

They ARE different issues and I can raise a separate one for the repetition one if that is what you suggest, but they are connected by the same cause according to my tests. That's why I mentioned them both.

**Comment by alex20114349** [comment]
Okay, the problem persists, but not in the same action. The actions that have modules that affect them like Coach don't have the issue anymore, as I said, but I am now getting a persistent yes registering as no any time I say yes to a girl asking to date me and specifically on that action when initiated by an NPC. Asking an NPC myself works fine as do all other actions. This happens even on classes with no modules applied at all.

**Comment by alex20114349** [comment]
It seems ALL of the after school stuff, like the arcade, are bugged as well in AA2MiniPPX. No matter what I say, even waiting for the interaction to time out, it registers as yes and begins the interaction. This was on a completely module free game.

**Comment by k4yf0ur** [comment]
Test it out by disabling triggers and modules and reconfirming the issue
![image](https://user-images.githubusercontent.com/35668308/120928117-a1d68b00-c6e3-11eb-9ef7-13229a0befdf.png)

**Comment by alex20114349** [comment]
I'll test that the next chance I get on my modded class just to make sure I'm testing a class with modules applied and the option off specifically. It hasn't happened with unmodded classes, but that isn't necessarily the same.

**Comment by alex20114349** [comment]
Tested, no module based interaction at all as it should be, which includes a distinct lack of flipped yes/no answers, but this does still mean it's a module issue specifically, so I'll ask over on the Discord you pointed out.
