### ISSUE TITLE
Jizou statue silent crash

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#312]
The Jizou statue occasionally, but consistently, crashes the game while in use whether it is simply used by going from student to student on the favorability screen, switching screens to the stats screen (the second one with the H compatibility), or reading overall class statistics. This was an issue in the original as well, so might have been a quirk carried over from that. There is no log, there is no evidence except the event itself, it just shuts down while using the Jizou Statue and the windows I have open are resized down a bit when I do this and have to be manually resized to the proper resolution. This DOES affect both the portable and stationary Jizou statue abilities, I didn't have confirmation at first when posting this, but it literally just happened at the back of the school minutes ago and erased all progress I made for the day.

**Comment by linkanon** [comment]
This is most likely related to OOM when using PP2. The solution is to migrate either to a full install or to AA2MiniPPX

**Comment by alex20114349** [comment]
I have a full install. Unfortunately, not only does it have this issue, it has another one in the editor where the background is missing in the preview window, where the character you're editing is displayed, and is a solid pale blue and the card background is also this pale blue when produced. It also does not have the full HEXA set despite the files being in place. I'll look into AA2MiniPPX as that may be my only option other than to avoid the Jizou at all costs and take everything by surprise.

**Comment by alex20114349** [comment]
Testing so far looks good, I spent five minutes at the back of the schoool just toggling different students at the Jizou in both the favorability screen, the stats screen, and the H compatibility screen, switching to each screen, and toggling the statue screen on and off, no crash. That is not to say it is totally fixed and won't pop up again, it can sometimes take a while for this issue to come up, but I think the version I have now is good to go.
