### ISSUE TITLE
[Question, though possibly a module issue if the answer is no]

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#317]
Are certain modules that don't specifically say something about killing supposed to allow a girl to kill? I just had two girls make an attempt on a bully and both got arrested while only the second succeeded in the attempt. Their modules will be listed below to avoid any misunderstandings.

Girl 1 (first to attempt, failed and was arrested) [Admires Fit, Admires Wit, Agreeable, Armed, Cautious, Charismatic, Coach, Cupid, Decisive, Dependable, Dominant, Flasher, Loving, Loyal, Marriage, Martial Artist, Observant, Pheromones, Pregnancy, Tutor, Vengeful]

Girl 2 (second to attempt, succeeded, but was arrested in the process) [Admires Fit, Admires Wit, Agreeable, Armed, Cautious, Charismatic, Coach, Controlling, Cupid, Decisive, Flasher, Loving, Loyal, Marriage, Martial Artist, Observant, Pheromones, Pregnancy, Tutor, Vengeful]

Neither of them had a lover that was killed, these two attempts were the only two in this save. The first was never raped, she was still untouched even by me, her lover at the time. The second was touched, but as the lover of the bully that was killed until she broke up with said bully and I took her into my harem. The only module in common, and these two were not the only ones in the save with it, was Vengeful, but that is specific to lovers of murder victims. Nobody in this class was evil except the bully herself, who was the one killed.

**Comment by k4yf0ur** [comment]
Module issues aren't maintained through this github. Consult the [modclub](https://discord.gg/N37M9Ny) instead.
