### ISSUE TITLE
Severe lag with a class containing modules

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#318]
Any save where my class has modules lags even more than the Windows 10 d3d9 lag issue, this cuts off at no more than eight cards in play including the PC card. This is on a PC that handles unmodded full classes just fine. This occurs on all AAU installation types (AA2Mini, AA2MiniPPX, or AAU on an original installed copy of the game). It does not matter how many modules or how many of the cards in play have them, even just the PC card having them with more than eight total cards in play will do this. It is not a specific module doing this, either.

**Comment by Nuk3R4z0r** [comment]
I have this exact problem too. It seems to be worsening the longer my save games have been played. I think it has something to do with the calculating the set mood an npc shows when they are rendered upon approach and the calculation of the outcome of an interaction.

Saying "Let's all..." will make the game stall for 10-20 solid seconds on a game that has been played for an ingame week.

I too have tried different version of AA2Mini and the redistributables needed (c++ and dekstop).
It might be biased, but I think it makes it less worse to play with:
Windows Desktop 3.1.14.29915
C++ 2015-2019 x64 14.27.29016
C++ 2015-2019 x64 14.28.29914

I have a hunch it really started getting bad with 1.6
If someone needs me for debugging the issue further, reach out.

**Comment by k4yf0ur** [comment]
Try this build in which we addressed this [issue](https://github.com/aa2g/AA2Unlimited/releases/tag/v1.7.2)

**Comment by alex20114349** [comment]
If it were the calculation of moods, wouldn't it be acting up regardless of modules? Unless, of course, you specifically mean mood changes made by the modules, but then it begs the question of why that change in mood is acting any different than a mood change in an unmodded game.

I will attempt the build suggested to see if that works once I get a chance to update my test copy. I didn't even notice an update had happened, though to be fair this was reported while the latest build was 1.6.

**Comment by alex20114349** [comment]
99% taken care of, it still has a few frame drops here and there every few seconds that are not there on classes with no modules in play, but the game is not a slideshow anymore.

**Comment by k4yf0ur** [comment]
Sweet!
