### ISSUE TITLE
Error after installing the latest patch please help

### ISSUE THREAD

**Issue by toukent23** [aa2g/AA2Unlimited#320]
![1](https://user-images.githubusercontent.com/83888889/117555798-3dff6a80-b030-11eb-8e13-0af12b9703c5.PNG)
After downloading the latest patch, I keep getting this error whenever I try to launch the game or editor. It roughly translates to:

 "The configuration file could not be read, so the configuration file was initialized." 

Anyone knows what this means and how to fix it?

**Comment by k4yf0ur** [comment]
The latest patch to what? Updating AAUnlimited properly shouldn't have caused this. How did you install the game?
