### ISSUE TITLE
[Question] Crush Module, how to set it up

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#322]
The Crush module states that I should unpack it, I hit unpack on the modules tab in Edit. All it did was do the blink and send back to the top of the list of modules that it does when applying a module and I cannot see any file or anything to indicate any difference. However, I AM able to edit the file in the module folder using a text editor. When opening it in a text editor, it shws the description and multiple single words referring to crush, trigger, and crush's name with a bunch of boxes like it couldn't identify those characters. My question is where this "Crush's Name" I'm supposed to be changing is and if I'm doing it right by going in with a text editor. The last thing I want to do is mess it up even with a backup in place. An image will be supplied to help show what I'm talking about.
![Untitled6](https://user-images.githubusercontent.com/59283313/117747973-274a4680-b1dd-11eb-83fc-c6e01d2fd06b.png)

**Comment by k4yf0ur** [comment]
Module issues aren't maintained through this github. Consult the [modclub](https://discord.gg/N37M9Ny) instead.
