### ISSUE TITLE
Banchou Bug

### ISSUE THREAD

**Issue by alex20114349** [aa2g/AA2Unlimited#323]
I literally just got out of a save, by ending the game without saving specifically to reverse the issue, and in that game one of my gang members asked to become lovers with a girl outside my gang. The description of the Banchou module specifically states they cannot do this, so the Banchou module is not working correctly. To combat this in the future while I'm working with the bugged version of the module, I'm also giving gang members the singleminded trait to ward off that specific action being used or accepted by gang members, I don't care if they can't do it to each other as a result. As a result of this change, I do not have a save to provide without reversing my own changes.

**Comment by k4yf0ur** [comment]
Module issues aren't maintained through this github. Consult the [modclub](https://discord.gg/N37M9Ny) instead.
