### ISSUE TITLE
Help with launching game and making 'ppx' files...

### ISSUE THREAD

**Issue by xayneg** [aa2g/AA2Unlimited#327]
Well finally I decided to update my game after one year of no updates, and got AA2MiniPPX but it doesn't seem to launch properly. Before deciding to post here about it, I've looked for similar posts and found a "solution", I moved the game's folder to root (i.e. C:\illusion\AA2MiniPPX), even so the game still doesn't launch upon clicking "launch game" from AA2Play.exe, I can make it run through "manual launch" of the PPeX, but then after executing the game.exe and hitting "launch game". somehow the "pipe" still connects but another cmd shows up (image below). Can someone tell me how do I fix it?
![Error1](https://user-images.githubusercontent.com/84001203/118393981-2a8b6b00-b5ff-11eb-90ee-e4fa19f10618.png)
And the second issue is, how do I make 'ppx' files properly?
I tried making one out of 'pp' files but got a big file after it ended, something I did wrong?
My exact command was: ppexcli -c "folderdirectory" file.ppx
Said folder had only 'pp' files, and the output 'ppx' was way too big...
Thanks in advance!

**Comment by k4yf0ur** [comment]
Ensure that you've installed everything from the extra folder that comes with PPX Mini.

Packing files from a single folder:
ppexcli -c "pathtomod\*" output.ppx

Packing files ready for AA2Install:
ppexcli -c "pathtomod\AA2Play\*" "pathtomod\AA2Make\*" output.ppx

Unpacking files
ppexcli -e "pathtofile\ppex_file.ppx" "c:\some_export_folder"

**Comment by xayneg** [comment]
> Ensure that you've installed everything from the extra folder that comes with PPX Mini. Also, you can't run two instances of the game - so you can't launch both aa2play and aa2maker at the same time.

How do I even do that? I'm only launching the "AA2Play.exe"... Also I already installed everything from there, gonna redo and reinstall everything to test out.

For the ppx file. I see, the "*" is necessary... So to make a ppx file out of a pp only folder, do I use the very first command or how do I use the second?  Just like the first one but adding .pp to the end?
TIA
