### ISSUE TITLE
Crash when loading high poly from roster or in game interaction

### ISSUE THREAD

**Issue by SaotomeRanma142** [aa2g/AA2Unlimited#335]
The game crashes when clicking on a character from the roster to edit their clothes or as soon as you try to interact with them in-game. Worked under previous version 1.6.1. Tried with all win 10 fixes and without, same result.

Rename the attachment to .7z to unpack.
[AAUCRASH.zip](https://github.com/aa2g/AA2Unlimited/files/6601662/AAUCRASH.zip)

**Comment by k4yf0ur** [comment]
Try this https://github.com/aa2g/AA2Unlimited/releases/tag/v1.7.1

**Comment by SaotomeRanma142** [comment]
Sorry, it did not fix the issue.

**Comment by k4yf0ur** [comment]
Can you send me the card that is causing the issues?

**Comment by k4yf0ur** [comment]
Also, inside your data folder, there's a save folder. Go inside it, and then inside your class folder. Send me the .sav file and the associated .json file for the save game you are using as well.

**Comment by SaotomeRanma142** [comment]
Hello, 

It doesn't appear limited to a specific card. As requested, attached is the save file and json.
[class.zip](https://github.com/aa2g/AA2Unlimited/files/6602848/class.zip)

**Comment by k4yf0ur** [comment]
Awesome. Does it happen on any save file? If you start a new game and try, does it still occur?

**Comment by k4yf0ur** [comment]
Having tried the save, I can open the cards in high poly without issue, both by talking to them, and by opening them in the clothing selection screen. Can you post screenshots of the content your data folder, and of your AAUnlimited launcher settings?

**Comment by k4yf0ur** [comment]
Can you try setting the shadowmap settings to something other than none?
![Capture](https://user-images.githubusercontent.com/35668308/120903765-5b801e00-c648-11eb-85d8-9f9bb37a1b2c.PNG)

**Comment by SaotomeRanma142** [comment]
Not sure on the reason behind it but it looks like this did the trick.

Thank you!
