### ISSUE TITLE
Game launches and plays fine but overrides don't seem to be loading?

### ISSUE THREAD

**Issue by dartallis** [aa2g/AA2Unlimited#340]
Modded cards play without clothing overrides coming into effect. I'm on windows 10. I have newer versions of the redistributables and .net is installed.
Don't think I have ever launched and not had this pop up in the console window.
[ERROR] Failed to connect \\.\pipe\PPEX
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[WARNING] Waiting for server ready, status: False
[INFO] Using A:\AA2MiniPPXplayfolder\AAUnlimited\lib\reshade\dxgi.dll for graphics rendering.
[INFO] Entering main game event loop

**Comment by k4yf0ur** [comment]
That's normal for ppex. Post a screenshot of the overrides and a link to the card in question.

**Comment by k4yf0ur** [comment]
Oh, and post a screenshot of your AAU launcher settings.

**Comment by dartallis** [comment]
card in question https://db.bepis.io/aa2/view/55217
![overrides1](https://user-images.githubusercontent.com/85973501/122148607-c68bda80-ce28-11eb-91de-c872316b9d4d.png)
![overrides2](https://user-images.githubusercontent.com/85973501/122148613-c8ee3480-ce28-11eb-83cb-af1b4aabd1b9.png)
![overrides3](https://user-images.githubusercontent.com/85973501/122148618-cab7f800-ce28-11eb-9818-fca2c52a6a03.png)

**Comment by dartallis** [comment]
Launcher settings.

![launcher1](https://user-images.githubusercontent.com/85973501/122149240-c3451e80-ce29-11eb-9802-6f05a0052562.png)
![launcher2](https://user-images.githubusercontent.com/85973501/122149242-c3ddb500-ce29-11eb-8859-66024da4a192.png)
![launcher3](https://user-images.githubusercontent.com/85973501/122149245-c3ddb500-ce29-11eb-9c17-37ecf801a981.png)
![launcher4](https://user-images.githubusercontent.com/85973501/122149247-c4764b80-ce29-11eb-8302-a222ee8dbe4d.png)

**Comment by linkanon** [comment]
how does she look ingame?

**Comment by dartallis** [comment]
In game she appears in a blazer style uniform black with gold trim.

**Comment by linkanon** [comment]
pictures

**Comment by dartallis** [comment]
Top pic she is coming from the dojo/club, middle is class time, bottom is gym time. Didn't see a swimsuit set.

![AA2Play 2021-06-15 22-49-48](https://user-images.githubusercontent.com/85973501/122151182-15d40a00-ce2d-11eb-9c60-b8b1d040e55f.jpg)
![AA2Play 2021-06-15 22-51-21](https://user-images.githubusercontent.com/85973501/122151185-179dcd80-ce2d-11eb-98b0-7b46d682cc3d.jpg)
![AA2Play 2021-06-15 22-52-00](https://user-images.githubusercontent.com/85973501/122151187-18cefa80-ce2d-11eb-822d-b51629e67cbb.jpg)

**Comment by linkanon** [comment]
seems like she's wearing her cardface's outfit only during club. You simply don't have the base outfit so the game reverts to sailor. Class and sports seem correct

**Comment by linkanon** [comment]
you also don't have her personality

**Comment by dartallis** [comment]
Interesting.
If it's a mod card it wouldn't have the outfit baked in?
The personalities I'm not confident about playing with them just yet.

**Comment by linkanon** [comment]
it overrides a specific outfit, namely slot 172 as is evident by overrides
If you don't have the base outfit you'll see the sailor
I assume it uses 172 as a base simply for its low poly models

**Comment by dartallis** [comment]
Yes, that is what the card author mentioned on the card index sight.

**Comment by dartallis** [comment]
I believe I have found a version of the bikinis in question. Where would I have to put them, to make them work?

**Comment by linkanon** [comment]
the same place as you'd put any outfit: data
