### ISSUE TITLE
body slider keeps breaking the model

### ISSUE THREAD

**Issue by Dingofiz** [aa2g/AA2Unlimited#341]
Most of the sliders in the body slider tab don't work as expected. I keep having to get the model to reset in order to attempt any further modifications. Is there something on startup that I missed or something?

**Comment by k4yf0ur** [comment]
Probably, yeah. Did you follow the [modern installation guide?](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub)

**Comment by Dingofiz** [comment]
Apparently I wasnt supposed to use aa2install. Could be why some other mods were giving me problems. I'll try and be more thorough on the installation and see how it works out.

**Comment by k4yf0ur** [comment]
How did it go?

**Comment by Dingofiz** [comment]
The sliders seem to work fine now, even the ones with the asterisks. But I also have problem with play mode where custom characters take a long time to load during conversation (varying time with each character) and sometimes even crash the game. Should I open another issue for this?

**Comment by k4yf0ur** [comment]
Post the crash dumps. Are you using dgvoodoo2 or dxvk?

**Comment by Dingofiz** [comment]
Posting the crash dumps doesn't seem to be working, is there a certain way to post the file? I'm using dgvoodoo2, though, it seemed to be the optimal option.

**Comment by k4yf0ur** [comment]
What do you mean posting the dumps isn't working? Attach the relevant files to your post by drag and dropping the files, or upload them somewhere else and post a link.

**Comment by Dingofiz** [comment]
[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/6728447/aaucrash.zip)
Compressing the file seems to work. I don't know of any other files you may need or if this is the only one.

**Comment by Dingofiz** [comment]
There might be more than one reasons for crashing on the file. I think I remember it crashing in AA2Edit, but I can't remember what for.

**Comment by k4yf0ur** [comment]
Post a screenshot of your AAU launcher settings

**Comment by Dingofiz** [comment]
![Graphics](https://user-images.githubusercontent.com/86284066/123689682-59a11900-d808-11eb-864f-ecf85d71bd38.png)
![AA2Unlimited](https://user-images.githubusercontent.com/86284066/123689694-5d34a000-d808-11eb-9acc-6398de75efec.png)

**Comment by k4yf0ur** [comment]
Post a screenshot of the content of your data folder. 
Set the screenshot format to bmp. Download the new dgvoodoo I attached to the post, and put it in AAUnlimited\lib and override the files when asked.
[dgvoodoo2.zip](https://github.com/aa2g/AA2Unlimited/files/6728700/dgvoodoo2.zip)
Do you have an old PC? Play until you crash again, then attach the new crash dump.

**Comment by Dingofiz** [comment]
[data contents.zip](https://github.com/aa2g/AA2Unlimited/files/6728876/data.contents.zip)
I have an unremarkable 2014 Toshiba Satellite C75D.
Should I delete the current dmp file before playing?

**Comment by k4yf0ur** [comment]
You might as well remove it, sure, although aau replaces it by itself.
How much ram is that?

**Comment by Dingofiz** [comment]
I didn't know the file gets automatically replaced, I thought it just adds more crash reports...
I found out the crashes were from a problematic character card, but your modification did reduce most sprite load times. There's a noticeable performance drop during h-scenes now, though.
Also, I have 4gb ram.

**Comment by Dingofiz** [comment]
Actually, the game is still relatively the same. It just needed time to load.

**Comment by k4yf0ur** [comment]
And the crashes are gone?

**Comment by Dingofiz** [comment]
The crashes only happened to a specific character, which I got rid of for now. But I did get a alternative card to see if it would work
