### ISSUE TITLE
Crashes everytime 

### ISSUE THREAD

**Issue by SikNinjaK** [aa2g/AA2Unlimited#342]
[Crash Reporting.zip](https://github.com/aa2g/AA2Unlimited/files/6704459/Crash.Reporting.zip) Hopefully you can help shed some light on this problem. If the game starts at all without fail it crashes every time I try to talk to an NPC. I've followed the instructions for Windows 10 all the way done to trying all the settings in compatibility mode for Windows 8, 7, and even XP. Hopefully this isn't a dead thread. Thanks in advance for you help. And also thanks for a great game pack. It's impressive even if I cant get it to work I suspect that has everything to do with me and nothing to do with the game because the pack is solid. :+1: :+1:

**Comment by k4yf0ur** [comment]
How did you install the game? Did you follow this [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub)?
