### ISSUE TITLE
Launcher won't even start the game and keeps crashing

### ISSUE THREAD

**Issue by KyoArano** [aa2g/AA2Unlimited#346]
Hello, I tried following all the steps and solutions for this from this guide: https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub#h.a1jzvhomb78a

Although nothing seems to work, I installed direct x9 and all the other things too.

I managed to take a screenshot of what the launcher is trying to tell me but I just can figure it out myself!
![Screenshot (305)](https://user-images.githubusercontent.com/87676574/126235966-7ab9e90f-4f62-4bd8-8e43-592d5ebe243c.png)

**Comment by k4yf0ur** [comment]
Those messages are expected, they're not actual errors. Take a screenshot of the content of your extra folder and post it here. Ensure that you've installed everything from there. 
[Update ](https://github.com/aa2g/AA2Unlimited/wiki/Installation#updating)your AAUnlimited to the latest version.
Post screenshots of your launcher settings, all tabs.
