### ISSUE TITLE
AAUnlimited 1.7.3 Male transparent bug. 

### ISSUE THREAD

**Issue by hentaipost** [aa2g/AA2Unlimited#348]
Hi when I installed the newest patch I found a weird bug. When you make the male transparent the model kinda just goes all over the place. Example in my case his lower half kinda goes into himself and he has poles coming out everywhere, reaching out so far it goes through the girl character no matter what position, its a mess. 

Thank you guys for working hard on making this program and making my experience playing the game a enjoyable one. Hope you guys have a wonderful day.  

Sorry for any grammar mistakes I am dumb.

**Comment by k4yf0ur** [comment]
Does the bug persist after you revert back to an older version? Post screenshots of your data folder, and of the issue you are experiencing.
