### ISSUE TITLE
How can I use Triggers and Modules  in the game ?

### ISSUE THREAD

**Issue by cmtg994r** [aa2g/AA2Unlimited#350]
How can I use Triggers and Modules  in the game ?

**Comment by k4yf0ur** [comment]
[Modules ](https://github.com/aa2g/AA2Unlimited/wiki/Modules) - Modules are bundles of triggers that work as custom character traits. They don't merely modify the game's Ai, they add to it things that were previously not possible. Modules list with the download link is here.

Open a character in AA2Edit. In AAU window, click on modules tab and add modules to the character through it.
