### ISSUE TITLE
Game not patching to english?

### ISSUE THREAD

**Issue by MortuusUmbra** [aa2g/AA2Unlimited#351]
I did everything the install said but its just not patching to english. I also dont get the english subtitles option in the Unlimited settings tab either. I have the newest update.

**Comment by k4yf0ur** [comment]
Ensure your game is up to date and you have all the appends installed. Alternatively, check out the [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub).
