### ISSUE TITLE
Unhandled exception 0xE06D7363

### ISSUE THREAD

**Issue by PeachySunday** [aa2g/AA2Unlimited#355]
[Error logs.zip](https://github.com/aa2g/AA2Unlimited/files/7147011/Error.logs.zip)
I can't tell why or when it crashes but I've found it to happen in most areas and interacting with other characters. Get back to me if you have any ideas.

**Comment by k4yf0ur** [comment]
How did you install the game? Did you follow the [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub)? What variant of win10fix are you using?

**Comment by PeachySunday** [comment]
I followed the installation guide, im running the dgVoodoo2 variant and I would assume my AAU is up to date
