### ISSUE TITLE
dll error: dx3dx9_42.dll cant be found

### ISSUE THREAD

**Issue by lovecarol** [aa2g/AA2Unlimited#358]
i dont know why but i keep getting this dll error: 
![image](https://user-images.githubusercontent.com/91360641/134758768-ee5a3b6f-0e55-40d9-a0ad-5b046bd45749.png)

trad: d3dx9_42.dll cant be found. try to reinstall the program.

the closest i got to solving this was changing the directory name to "Illusion", wich gave me another dll error:
![image](https://user-images.githubusercontent.com/91360641/134758929-0e36c11c-53bb-4cd7-a18f-53cb60b30680.png)

but now is AAUnlimitedDLL, which i do have: 
![image](https://user-images.githubusercontent.com/91360641/134758953-c31cba68-10ab-40f4-a62f-5100782e83d3.png)

everything else:
![image](https://user-images.githubusercontent.com/91360641/134758976-babdc628-8cda-4c9f-8ad2-ba1d034433ee.png)

also when i try to patch the game i get this:
![image](https://user-images.githubusercontent.com/91360641/134759024-f0782655-e377-4f33-8a4c-5998b27ec601.png)

*game is located in my hard drive

**Comment by k4yf0ur** [comment]
You downloaded mini. Read the instructions on how to install the game [carefully](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub). You aren't supposed to be patching the exes, which the guide stresses. It comes with AAU preinstalled, so just [update](https://github.com/aa2g/AA2Unlimited/wiki/Installation#updating) AAU.
