### ISSUE TITLE
AAU crashing after interactions are initiated.

### ISSUE THREAD

**Issue by dartallis** [aa2g/AA2Unlimited#364]
[Crash Files.zip](https://github.com/aa2g/AA2Unlimited/files/7376914/Crash.Files.zip)
![1 7 4_AAUnlimited_after_update](https://user-images.githubusercontent.com/85973501/137998158-17a1c74f-b2ee-4eb4-aacc-eee476428182.png)

**Comment by dartallis** [comment]
![version](https://user-images.githubusercontent.com/85973501/137999268-a89872c0-c3f4-4720-a471-8b15963b112e.png)

**Comment by dartallis** [comment]
dgvoodo 2

**Comment by k4yf0ur** [comment]
Has the game been stable in the previous version of AAU? If so: download an older version of AAU where it worked and extract it on your desktop. Open the lib folder and copy dgd3d9.dll and dgVoodoo.conf from it. Paste these files in your actual AAUnlimited's lib folder and override.

**Comment by dartallis** [comment]
Okay I'll try that and get back to you. Thanks in advance for your guidance.

**Comment by dartallis** [comment]
Yup, I can interact again. On a side note the game worked with the update enabled until I interrupted a guy hitting on the pc's girl.

**Comment by k4yf0ur** [comment]
Thanks for the info. Let us know if you run into any more issues.
