### ISSUE TITLE
Some personalities could not play voices in fields.

### ISSUE THREAD

**Issue by UndefinedClass** [aa2g/AA2Unlimited#367]
There is a problem about 'a66 AA1 Selfish' and 's76 AA1 Manly'.
Their voice files can not be played in NPC-NPC talk, so subtitles also don't work.
I try to change the slot number of them, then it works.
However this solution is limited to only my own use.
So I wonder that this issue could be fixed later.
Thanx.

**Comment by k4yf0ur** [comment]
That sounds like an issue with the personality mod itself, not AAU. But I'll let whoever is managing that mod know about the issue, and hopefully they fix it!
