### ISSUE TITLE
Penis Out of Position in Sex Scene

### ISSUE THREAD

**Issue by Jaraporn** [aa2g/AA2Unlimited#371]
Some Bj moves' penis are misplaced or maybe shorter
![1639025094062](https://user-images.githubusercontent.com/95839072/145336106-34f2cf75-84f7-474f-9470-0ec5fc8a17a8.jpg)
![6](https://user-images.githubusercontent.com/95839072/145336114-9b9b0cd1-43e2-4604-9211-2334be52cbec.jpg)
![1639025017208](https://user-images.githubusercontent.com/95839072/145336119-da9575fd-14d8-4636-bb18-d111198a4a80.jpg)
![1639025035160](https://user-images.githubusercontent.com/95839072/145336122-25eb2542-8f87-462b-88f6-7124075a45ab.jpg)
r

**Comment by k4yf0ur** [comment]
This is not really an AAU issue per se, but an issue with the mod you're using. I believe the authors are aware that some positions are misaligned, and working on it.
