### ISSUE TITLE
Make a v0.3 release

### ISSUE THREAD

**Issue by linkanon** [aa2g/AA2Unlimited#39]
As it stands Test11 is a functional and more or less bug-free version. I suggest making a full-blown official release for it.
Test12 would have triggers and styles/sets: major features that would most likely be very broken at launch. Now's the best time to make an Official Release™ while it works.

Me and @geneishouko already agreed on it so I'd like @AA2Hackanon 's input. Also I could manage the releases myself if you want.

Only major releases should be in the Releases tab imo. All the intermediate test# releases would still be released like always. Might even follow a proper versioning system: v0.3.0.1, v.0.3.0.2, etc. v0.3.1 would be the official hotfixes if we messed up in some obvious way for release.

**Comment by geneishouko** [comment]
>Only major releases should be in the Releases tab imo.

We could put test releases here as well and remove them at the final release.

**Comment by AA2Hackanon** [comment]
i assume you want a release to combat the people that download the things under the release tab here. Im not sure what is part of test 11, if its been released already and how you would manage to keep the trigger changes out of it (considering that they are already on the master), but if you are willing to put up with those headaches, feel free to put up any releases you see fitting.

as for the version numbering, i wouldn't put too many thoughts into it, its not like it matters for a hobby project. i mean, the test releases only have a single number, and nobody seemed to mind

**Comment by linkanon** [comment]
Published [v0.3.0](https://github.com/aa2g/AA2Unlimited/releases/tag/v0.3). Essentially repackaged test11 - everything until triggers.
