### ISSUE TITLE
After updating from aaminiv12 the game starts but its just white or black screen

### ISSUE THREAD

**Issue by hujciwdupegithub** [aa2g/AA2Unlimited#394]
the music still plays but theres nothing in the window except black or white. updated the way its described in the how to update guide. Im using aa2mini since the ppx version doesnt work for me

**Comment by linkanon** [comment]
we abandoned pp2 and aren't supporting it anymore

**Comment by hujciwdupegithub** [comment]
fair, now excuse my lack of any knowledge but is there a chance updating aau from the torrent to the latest one would fix the startup crash?Im dealing with the win10 shit and any of the fixes in faq didnt work for me

**Comment by linkanon** [comment]
I can't tell why you're crashing after updating AAU. Crashes on launch usually happen when you're using PPeX but you failed to install the prerequisites.  Since you're using an old AA2Mini, which was based on .pp2, this does not apply to you

**Comment by hujciwdupegithub** [comment]
I only switched to the old one after trying the torrent one from the modern guide which crashed at the start

**Comment by linkanon** [comment]
then you didn't follow the instructions properly. The modern guide tells you to get AA2MiniPPX(note the PPX in the name, meaning it's using the new format), then install all the dependencies in the `extra` folder

**Comment by hujciwdupegithub** [comment]
im gonna try again then thanks
