### ISSUE TITLE
dmp file error

### ISSUE THREAD

**Issue by clsiddl** [aa2g/AA2Unlimited#395]
I'm playing this game, and the moment I press it to see the character in the character selection window, this message appears and the game turns off.
![dd](https://user-images.githubusercontent.com/99365158/153475861-31d8f6d8-0ed4-4308-a046-6bc4dc409a4c.png)

[3files.zip](https://github.com/aa2g/AA2Unlimited/files/8043527/3files.zip)

**Comment by k4yf0ur** [comment]
What version of AAU are you using?
