### ISSUE TITLE
Crash when characters are interracting and they're bald

### ISSUE THREAD

**Issue by Meraalia** [aa2g/AA2Unlimited#402]
So i installed the game and when i play it, the characters of school are bald and some are T posing, when the PC and an NPC interact i have an error message 

![Capture d’écran (311)](https://user-images.githubusercontent.com/102191524/159587011-34c74e58-bffe-47b4-aee2-1254c955aa4b.png)

I tried to uninstall and reinstall AA2Play and AA2Unlimited but nothing worked, if someone knows what to do please tell me !

**Comment by geneishouko** [comment]
Most likely your install is missing many important files. Please get the latest AA2Mini and extract it in a clean folder. If that works you can build up from there by adding mods and more stuff.

**Comment by geneishouko** [comment]
Don't run the game as administrator

**Comment by Meraalia** [comment]
It's still not working ;-;

**Comment by Meraalia** [comment]
update: I uninstall and reinstall everything again and now the characters just does not appear :/

**Comment by Galm03** [comment]
> update: I uninstall and reinstall everything again and now the characters just does not appear :/

Try checking if you have C++ redistributable installed. I was having the same issue, but I found out that I didn't have it installed. Make sure it's up to 2015, at least, and try launching the game.
