### ISSUE TITLE
Freeze/Lag for a few second after a conversation starts

### ISSUE THREAD

**Issue by Velrym** [aa2g/AA2Unlimited#405]
Pretty much the title. I really don’t know what could be causing it. Tried messing around with the launcher settings (AAmini) but it doesn’t really effect performance. (Same goes for antialiasing/mipmap/shadowset settings.) Any ideas on how to fix this?

**Comment by k4yf0ur** [comment]
It's loading the assets. Nothing we can do to speed things up, this is just how the game works by itself.
