### ISSUE TITLE
Help! Position, AA2MiniPPX

### ISSUE THREAD

**Issue by Dregcha** [aa2g/AA2Unlimited#407]
Hello, I have a problem. Downloaded AA2MiniPPX, updated AAUnlimited to 1.8.0 from GitHub. After that, with scenes H, I can't change positions. The name of the position is in the upper left corner and there is no way to click on it. What could be the problem? Sorry for my English.

**Comment by linkanon** [comment]
bad JMCP setup. Remove everything relevant and read the new JMCP readme

**Comment by Dregcha** [comment]
I'll try, thanks. Can you give a link to the new one, if it's not difficult for you?

**Comment by Dregcha** [comment]
I'll try, thanks. Can you give a link to the new one, if it's not difficult for you?
