### ISSUE TITLE
Hello again. Position. AA2MiniPPX.

### ISSUE THREAD

**Issue by Dregcha** [aa2g/AA2Unlimited#409]
Hello again. I asked here about the positions earlier. The problem has not been solved. I reinstalled the game, I didn't install JMCP. Updated AA2MiniPPX to AAU 1.8.0. Decided to check whether or not positions will work without JMCP. When I enter scene H, the positions are in the upper left corner. I also don't understand what it means in JMCP to disable the H_filename.lst files in the readme when installing this mod. Sorry for my English.

**Comment by linkanon** [comment]
if you had that issue without JMCP then you probably had the screenshot format set to .bmp
Change it to .jpg or preferably .png

**Comment by Dregcha** [comment]
Okay, I'll try, if the problem remains, then I'll write
