### ISSUE TITLE
Black Skin/Clothing

### ISSUE THREAD

**Issue by Asmiroth** [aa2g/AA2Unlimited#410]
I'm running PoP OS, running through Wine using Lutris.  I've tried nearly every combination of setting I can think of.  
Wined3d  - Looks fine, stuttering/laggy.  
Win10fix (dgVoodoo 2) - Weird black skin/clothing in random combinations, runs fine from what I can tell.
Win10fix (DXVK) - Looks fine, stuttering/laggy.  

I've noticed that when nude, the skin shows alright, but some parts of hair and fingernails/toenails are black.  Posting screenies if anyone can help me in the right direction, I'd appreciate the help.
![what](https://user-images.githubusercontent.com/103337510/162592704-06307cd4-4a30-4923-abb4-65376d4ae1de.png)
![what2](https://user-images.githubusercontent.com/103337510/162592717-cb758ddd-8390-4f83-8f43-b42d1645aee0.png)

**Comment by notsafeforbread** [comment]
Appears to be a regression in DXVK 1.10. In Lutris you should be able to change the DXVK version back to 1.9.4.

**Comment by Asmiroth** [comment]
That was it.  Thank you, notsafeforbread!
