### ISSUE TITLE
Having a system error. 

### ISSUE THREAD

**Issue by Tweetsie12** [aa2g/AA2Unlimited#412]
Hello. I'm trying to run the game, but I keep getting this error when I try to open the AA2Play.exe or AA2Edit.exe folder. Can you help me out here? Thanks!
![image](https://user-images.githubusercontent.com/84629804/163510772-629d4838-cc4e-4b58-864a-2e92caf69aa5.png)

**Comment by k4yf0ur** [comment]
It looks like you didn't follow the [installation guide](https://docs.google.com/document/d/e/2PACX-1vS8Ap6CrmSNXRsKG9jsIMqHYuHM3Cfs5qE5nX6iIgfzLlcWnmiwzmOrp27ytEMX03lFNRR7U5UXJalA/pub) very closely. Install the requirements.
