### ISSUE TITLE
Male character's emotions

### ISSUE THREAD

**Issue by Dregcha** [aa2g/AA2Unlimited#422]
Hi! During scene H, the male character's emotions are constantly changing at a tremendous speed. I can't figure out what the reason is. Is there any way to fix this? There's nothing wrong with the female characters' face. Sorry for my English.

**Comment by k4yf0ur** [comment]
This is not an AAU issue, it's missing voice lines during h scenes. But a fix can be found [here](https://mega.nz/folder/Q7gmmIKQ#nLBesauyHcxSC1gR6UyLRg/folder/5mYjnYjT).
