### ISSUE TITLE
Any fix/solution?

### ISSUE THREAD

**Issue by xayneg** [aa2g/AA2Unlimited#434]
It seems that 'harderlinker' is not working... I run the .bat file and the console shows that it's working and while all the folders and shortcuts are created, it doesn't reflect the textures once running the game... Anyone knows what's happening?
The console shows the following:
"ECHO is off", "System could not find the specified file", "Access denied", "Binding created for XX <===> YY".
![ERROR2](https://user-images.githubusercontent.com/84001203/180582270-cc1eb116-f06f-444a-a109-ed9b9cb675fc.PNG)

**Comment by linkanon** [comment]
Are you running the .bat with admin rights? Don't do that
Also, what OS?
The echo messages and some errors are expected and normal - they're the result of a weird syntax.
Harderlinker's .bat doesn't actually populate the folder with textures. It just creates the required folder structure. If you're getting the links created try opening some of them and check that they're actually pointing towards some folders

**Comment by xayneg** [comment]
No, am not running it with Admin rights.
My system is Windows 10 Single Language.
Yeah I noted that these msgs are also shown on older versions of "hardlinker/harderlinker". 
I pretty much know how 'harderlinker' works tho I don't know anything about programming/coding...
So it should be that option at the end. Damn it even tells you what it does, now I feel dumb. lol

Anyway, that's obviously gonna work but just in case, gonna edit this comment if it worked (which will be).
Many thanks linkanon to even reply me with such trivial issue. Have a great day.
