### ISSUE TITLE
Feature Request: Body Sliders Reset/Notches

### ISSUE THREAD

**Issue by DarkPulse** [aa2g/AA2Unlimited#47]
Found out about this and it coaxed me into reinstalling this old project that I partially helped worked on translating/editing. It's highly impressive people have hacked it this extensively. A poser! I would've been so, so happy to see this back in the day. (A full-fledged studio would be amazing... but maybe a bit unrealistic, meaning PPD will have to remain the best studio for Yayoi, probably.)

Anyway, I began tinkering with the newly-expanded character stuff, but one thing I found irked me - if you adjust sliders, there's no real quick and easy way to reset them, or to have any sort of gradation/steps - it's all smooth unless you enter an exact value, and any/all resetting is done by manually highlighting the number and setting it to zero. Worse, the field doesn't even accept Ctrl+A, so you have to manually highlight the value with mouse to set it to zero.

This is a couple moves too many for when you just want to see what a value actually does and how it makes your character look. There's more than enough room for a "reset" button here, next to each entry field, or at least make it accept Ctrl+A so we can click in the field, select all, and smack a zero (although a reset button would be quicker still).

PS: Zetthigh Ryouiki made me smirk, but it's both perhaps a little deceptively named (and some might argue too weeb). Especially as it's got nothing to really do with actual Zettai Ryouiki. Although I admit it's hard to think of what else it could be named, given the multiple thigh bits.

PPS: It's ironic seeing one of the creators of this project nicknamed after a name I translated... and Gen'Ei isn't even a proper fucking name - 幻影 literally means "phantasm/illusion/apparition." That is, it was Illusion being a bit cute.

**Comment by geneishouko** [comment]
Sliders indeed could get some love and additional ease of use. That's planned and may come out in the next release. We're just 3 persons hacking this project together. Regarding steps, doesn't clicking on the slider bar on the know sides accomplish this? Keyboard ease of use is another known issue that we haven't researched very well. Keep in mind that portions of the current UI are being phased out for a more modern one.

PS: ZR was indeed what I had in mind regarding that slider but results weren't what I expected and I kept the name, which I liked.

PPS: It isn't Ironic when I named myself after the default girl and your chosen translation :^)

PPPS: What would be missing in your opinion for the poser to become a full-fledged studio?

**Comment by linkanon** [comment]
Hey

Not sure what you mean by full-fledged studio. Poser allows for random props, rooms, any number of characters(up until your PC blows up, that is) poses presets and soon scene presets. What it lacks is lighting controls, direct on-screen manipulation of limbs and animation controls. All of which are feasible.

Sliders reset buttons are already planned but the whole maker AAU UI is subject to complete rewrite so it's probably better to not do the same work twice. As you already figured out to reset you have to drag the slider, click the field and set it to 0 or 1(depends on the slider, most of them default to 0). When focusing the field it usually selects the whole thing so Ctrl+A is unnecessary. Also double click does the same thing.
If you want discrete steps you can click on the slider left or right of the caret. It increments/decrements it by 1% of the whole range i believe.

Zettai ryouki actually moves the height of the thigh-highs. Doing so usually warps them a bit though. Mechanically it's a `Thigh Height` slider.

**Comment by DarkPulse** [comment]
@geneishouko: Yeah, I'm aware of the rewrite that's ongoing. Presumably it's why I can't really move body parts yet in the poser... either that or I'm very confused as to how it works - there's very little documentation on it pretty much anywhere and I had to google up even how to activate it. (I know it's early on and just a few dudes hacking the project together, but documentation saves a LOT of headaches - trust me, we learned that very fast when doing CM3D2 and ReiPatcher...)

If you feel you want to make this more of a "proper" studio, one thing that would majorly help would be having a movement/rotation axis for objects and limbs. If you've played any of Illusion's games from HaremMate on and spent any time in their studios, you know exactly what I'm picking about - you pick your limb, and you get (depending on what you pick) either a movement "cube" that lets you click+drag to move it along the X/Y/Z axis, or a set of rotation "rings" that you can click+drag to cause the limb to move/flex in its given rotation direction. Basically, the sorts of things you get to do IK/FK-style posing.

If not, here's some images from Honey Select Party's StudioNEO. (Along with a translation of mine that probably won't ever get released due to me using ReiPatcher for it and everyone else still sticking with frigging Illusion Plugin Architecture despite the superior methods of ReiPatcher. >_>)

![image](https://user-images.githubusercontent.com/5454684/31304933-e734dfc4-aafb-11e7-9b57-8e1b41767347.png)

![image](https://user-images.githubusercontent.com/5454684/31304934-f9e2db30-aafb-11e7-98ca-44076c72514e.png)

Based on what I've seen online, with people giving their characters custom poses, you can totally do this now (...I think? Again, I can't get things to properly move for love or money, so either it's busted or I'm doing it wrong...) but it's definitely a lot easier (at least for me) if you can just pick your bone/limb, move it and rotate it into position as you need, and there you go, pose done.

I'm also still trying to figure out how (in AA2Make) how to make it save the pose I pick/select, as when I save a character, it isn't giving them that pose. Or would I need to use AA2Snowflake for that? (Though given how you're trying to replace all the old EXEs' functionality, this may be on the docket already - or, again, I'm doing something wrong. :stuck_out_tongue:)

@linkanon: As I said, the movement/rotation axes would help me, as right now I'm not sure if I'm even messing up or if the movement functionality for posing is busted - presumably that's what you mean by "direct on-screen manipulation of limbs." (Then again, I'm not sure if AA2 has any FK/IK to make use of... I think it does? You've got bones, after all, and that's needed for that...) I still haven't figured out how to add more than one character, either.

As for my other issues, when I focus on the field, it doesn't select the whole field. Ever. If it did, that would've been easy - click field to highlight all, type a 0 or 1, and voila, reset. Double-clicking, however, does work, so I will have to try to remember that for the near future. Thanks.

I'm trying not to be a newb when it comes to this stuff, but it's definitely dampening me a bit to have this neat poser that I always wanted in AA2, and then to not be really able to use it. Whether that's due to something being busted, me derping and not understanding how this thing works, or due to the rewrite, I'm not sure.

But I'm definitely taking notes whenever and wherever I can. :stuck_out_tongue:

**Comment by geneishouko** [comment]
There's a discord channel for real time tech support, you know. The link is in the project's README.

Have you actually opened the poser? (press the F12 key) It should give you a list of all the bones you can pose. Select a character, a bone and move the sliders.

> I'm also still trying to figure out how (in AA2Make) how to make it save the pose I pick/select, as when I save a character, it isn't giving them that pose. 

You can't. The maker resets the pose by itself on card saving.

The game doesn't have IK and we don't offer it either. We did have circle guides for posing at some point but temporarily lost the functionality in the move to the new poser.

**Comment by linkanon** [comment]
@DarkPulse 
IK is not implemented yet and probably won't be any time soon. And it would be a mandatory feature if you want to move the boxes on screen and have your limb follow them. FK, on the other hand, is how we pose our stuff now. You select your bone, select `rotation` in the operations list and drag the sliders. 

My mistake about the auto-highlighting. In my brain I just default to `drag`, `double-click`, `type in 0/1`. 

Most of the adopters gather in /aa2g/ and 2chan's may and jun boards so you can ask there or in the dedicated tech-support discord channel.

@geneishouko @DarkPulse 
>>  I'm also still trying to figure out how (in AA2Make) how to make it save the pose I pick/select, as when I save a character, it isn't giving them that pose.

>You can't. The maker resets the pose by itself on card saving.

You actually can use custom poses on the card face. The game only resets the pose number but your adjustments to it when it creates a card face. So if you base your pose on the T-pose and disable the maker pose files the game would fail to load the personality's default pose, default to T-pose and keep your custom pose. I've created a shadow set for it that wipes out the maker poses: https://c.lewd.se/vD3K1b_%21maker_tposes.7z . Just make your girl, set the pose to 0, create a custom pose, enable this set and save. Can't control the camera location but it's easy to deal with.

**Comment by DarkPulse** [comment]
@geneishouko: Okay, I was missing picking the bone, and I can see why I was confused - the first thing I'd tried to alter were skirt bones (because flicking through poses made the skirt spaz). But, as I just now understood, apparently the skirt doesn't have bones (or they're not set up), meaning that I was very confused as to why nothing was changing.

@linkanon: That's good to hear it's possible, at least. I'll see if I can get it working. Camera location was generally (if loosely) easy enough to control anyway, just go by height of camera and whatnot.

**Comment by ezdiy** [comment]
> AA2Snowflake

The png can be already replaced by arbitrary one during a 'on.save_card' lua event and supplying your own png buffer. It's just that it's a such a boring feature nobody has written a script for it yet.

I think something can be done about the pose-on-save though - just screenshot of current edit view instead of the custom one aa2edit builds for the card.
