### ISSUE TITLE
Random crashing, usually during or after H Scenes

### ISSUE THREAD

**Issue by cupicode** [aa2g/AA2Unlimited#473]
So, for context: I'm not using MiniPPX, but rather MiniPP2. Mostly because I can't use MiniPPX even if I wanted to as even on a clean install it will not run since I'm on Windows 11. Does not matter at all what I try to do, it refuses to run so I've stuck with PP2. 
Recently though I've been getting constant crashing on PP2 no matter what when prior it crashed less (lol). Usually it occurs after 1-2 H scenes though I've had it crash even from loading a file and then trying to edit the outfits. I've tried every possible combination of win10fix and wine3d, with the best results being dgVooDoo, DXVK2, and wined3d. Other two just do instant crash.

My only remaining guess is that the ikemen face mod on my install is causing the issue, as I downloaded it recently since my install of PP2 didn't have it. Maybe its causing conflicts with some older mods I'm using that may need some updating but I don't want to go through all the effort only to be hit with another crash code.

Attached is the most recent crash dump and the error code message I managed to get a screenshot of but I don't know how much help it'll be.
[aaucrash.dmp](https://github.com/aa2g/AA2Unlimited/files/13930170/aaucrash.dmp)
![image](https://github.com/aa2g/AA2Unlimited/assets/149218987/b0439ee7-f263-4d92-8835-880b31eadcb2)

**Comment by prism2001** [comment]
1. PPX runs on windows 11. source: i am on windows 11 and can run ppx just fine. what are your hardware specs?
2. pp2 is unsupported afaik, devs only provide support for ppx
3. crashdump files are useless

**Comment by cupicode** [comment]
my specs are 
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz Processor
8gb RAM
NVIDIA GeForce Driver v535.98
which should be fine, it can run other games just fine. i'll try updating my driver bc its out of date though if thats the issue.. But everything else is up to date. 
i've seen issues opened of Windows 11 not exactly liking PPX and no matter what I did I couldn't get it to open :/ ik pp2 is out of date but its the only version that I can actually play atm until PPX is fixed so it sucks its also giving me temper tantrums now lol.

**Comment by cupicode** [comment]
closing this issue bc i figured out i missed downloading .NET for PPX like an idiot. my bad! ill post again if i encounter any more issues but everything should be fine.
