### ISSUE TITLE
Tried everything you've wrote (on install guide+closed issues), still not working 

### ISSUE THREAD

**Issue by HonestPolitics** [aa2g/AA2Unlimited#48]
Can't ask /aa2g/ since I'm banned pls halp.
I put the file in the same directory as AA2Play.exe, run bat, get a popup that says "Unhandled exception Code:0xC06D007E Address:0x7478B832 Do you want to write aaucrash.dmp?" and the cmd lingers for a few  seconds before closing. 

Even tried running as admin (which I know you said not to do but desperate times desperate measures) and I get "Run DLL There was a problem starting AAUnlimitedDLL.dll The specified module could not be found."

**Comment by ezdiy** [comment]
yes, please attach the dmp & join discord so we can troubleshoot more

**Comment by HonestPolitics** [comment]
Sweet. If my problem gets solved I'll post the solution for lurkers. 
[aaucrash.zip](https://github.com/aa2g/AA2Unlimited/files/1370595/aaucrash.zip)

**Comment by HonestPolitics** [comment]
Solved. 
I only had 64bit vc redistributables installed. Installing 32bit as well fixed the problem.
