### ISSUE TITLE
Face sliders don't update live

### ISSUE THREAD

**Issue by reeeg00** [aa2g/AA2Unlimited#56]
Hi there, thanks for the fantastic mod, but I find a problem that the body slider which is changing the face parts(eyebrow, eyes and mouth) doesn't work.
I have tried all sliders and all of them are working expect the slider of the face parts.
here is the screenshots of the eyebrow slider, have already try in both female and male character making mode but both of them doesn't work.

![image](https://user-images.githubusercontent.com/35408775/34910318-93e02f98-f8f5-11e7-9d3d-df2198822100.png)
![image](https://user-images.githubusercontent.com/35408775/34910321-9e776e94-f8f5-11e7-8c8e-bd1cf02e85fe.png)

**Comment by geneishouko** [comment]
It's a known problem. Face sliders have an updating problem and require a full model reload to see the changes. Just go to the Maker System tab and click on "Apply". This will make the Maker reload everything and then the sliders should apply everywhere. Do this every time you want to see the changes of the face sliders.

**Comment by budhiargomiko** [comment]
Sorry to reopen the issue, but it seems I'm still experiencing the same issues when sliding nose, chin, and jaws, even after pressing apply button on new system tab (on clothes panel, right?) or any other button which I deemed will reload everything...

**Comment by dpalacio** [comment]
Make sure you have and are using facesliders and that you aren't overriding them with other faces.

**Comment by budhiargomiko** [comment]
Yeah, I just trying to slide the Nose height slider, apply it, and nothing happened to the face. Is my issue did not happened on you?

**Comment by geneishouko** [comment]
It works here. You have to describe the context in more detail to solve it. What AA2 installation are you using, what face are you using, what overrides, what shadow sets, etc.

**Comment by budhiargomiko** [comment]
I see... it seems because I still using the old large version of AA2... When I experimenting on minified version, it works... Thank you for your help...
