### ISSUE TITLE
Issue when starting H-scene. 0x000005 or something.

### ISSUE THREAD

**Issue by breeze44** [aa2g/AA2Unlimited#67]
So, I'm too lazy to dig through the 4chan thread and I also don't have time to do so. 
That's literally what happens everytime it starts.
Well, basically, this is what I did.

-> Got AA2 v14 (pre-install) and patched it with the HF patch
-> Installed some uncensor mod (MKIII I think)
-> Got the two Append Sets + all the other DLCs by myself ;-;
-> Had a real hard time to get the HEXACC and HEXA hair pack mods (also to make these work together, for some reason)
-> Installed 3DRooms mod with AA2Install
-> Installed AA2Unlimited _just like it's meant to be installed._
-> Game crashes every H-scene.

P.S.: I might have forgotten some important steps, but bear with me. I got this game in 2016.
P.P.S.: This text is also written on the .info file inside the zip.

[hate.zip](https://github.com/aa2g/AA2Unlimited/files/1671696/hate.zip)

**Comment by linkanon** [comment]
There's too many wrong things with what you did.
I suggest you save what you have(cards, saves) and start anew. Got to /aa2g/ get the fresh preinstall and install the mods.
**Don't use HF patch**
**Don't install DLC**
**Don't install anything included in the pre-install**
Follow the guides in the /aa2g/ OP
Read the readmes.

Your immediate problem is probably because of your messed up MCP and 3D Rooms. It's unrelated to AAU.

**Comment by breeze44** [comment]
But what's the problem with the DLCs? And how am I going to get these personalities back without these?
I'm a total noob to the AA2 modding community.

**Comment by geneishouko** [comment]
I checked the crash dump and it shows it's no AAUnlimited error. This actually is the typical crash caused by incomplete H scene mods.

**Comment by linkanon** [comment]
The DLCs are included in the preinstall. It's a fully-functional game.

You said you installed it in 2016 and many things changed. Basically it got almost trivial to get into the game as long as you read the readmes of what you're installing. 

All the info is gathered in the /aa2g/ OP so open that, get preinstall try running it and then follow the recommended mods guide. Also they're used to tech-supporting newbies so you can just ask them for help.
