### ISSUE TITLE
Position Issue: Evil AI + Homosexual

### ISSUE THREAD

**Issue by paynuts** [aa2g/AA2Unlimited#74]
With H-AI, Evil Lovers and Unlocks -> Homosexual activated: 

If a male player character becomes the target for a forced interaction, the initiating male NPC takes the submissive role during H which frankly seems a bit weird to me. 

A role swap isn't possible since in forced H the player can't use the UI. Is this working as intended or a possible mod conflict?

**Comment by geneishouko** [comment]
The game treats hetero and homo(lesbian) sex different. It assumes when that when the NPC is male the sex scene is an hetero one. It probably is fixable but is not on anyone's agenda right now.
