### ISSUE TITLE
Can't run install.bat

### ISSUE THREAD

**Issue by PineappleOnPizza** [aa2g/AA2Unlimited#80]
As the title says. After double clicking install.bat a window opens and closes immediately.
I have both 2015 redistributables installed and I'm running Windows 10.

**Comment by linkanon** [comment]
Try running the .bat from the command line. If it complains about missing rundll32 then you have to edit the .bat and explicitly point it to your rundll32. This happens when your system has broken PATH environment variable

**Comment by PineappleOnPizza** [comment]
It appears to be an issue on my part with cmd.exe, but for now I managed to circumvent the problem using PowerShell. Thank for the help.
