### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by DandyDonny** [aa2g/AA2Unlimited#87]
I found the mod two days ago and ever since then I have been trying to get it to work on my laptop.

At first it would only patch AA2EDIT and would fail to patch AA2Play
After I reinstalled the game due to a modding mishap it refuses to patch either due to permission being denied. 

[Whenever I move the folder](http://prntscr.com/ioax78)
 
Please help. I really want to use this mod.

**Comment by geneishouko** [comment]
Friendly reminder to give out as much information as you can. This report barely works to get to help you. As to the patching failing on AA2Play, please use the original and unmodded AA2Play launcher for that. Should that still fail, provide more information on all the things you pointed above and we may be able to get somewhere.
