### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Indignator** [aa2g/AA2Unlimited#88]
First time i clicked in "install.bat" it started and showed the directory, but when i clicked in "ok" it suddently closed, and nothing happened. Now when i try to install again the bat file open but close instantly and create a file named "logfile".
Here is the file, it says:
[CRITICAL ERROR] error loading module 'iupluacontrols' from file 'D:\Games\CoisasAA2\AAUnlimited_v0.6.5\AAUnlimited\lib\iupluacontrols53.dll':
	Impossível localizar o módulo especificado.

stack traceback:
	[C]: in ?
	[C]: in upvalue 'old_require'
	D:\Games\CoisasAA2\AAUnlimited_v0.6.5\AAUnlimited\init.lua:596: in function 'require'
	...CoisasAA2\AAUnlimited_v0.6.5\AAUnlimited\mod\patcher.lua:86: in function 'patcher'

[logfile.txt](https://github.com/aa2g/AA2Unlimited/files/1798969/logfile.txt)

**Comment by linkanon** [comment]
Your antivirus might've removed necessary .dll
It's a case of false-positive - whitelist it

**Comment by Indignator** [comment]
I checked the folder and the iupluacontrols53.dll its in. My antivirus has moved to analysis but i whitelisted and placed back on the folder,
Thanks for you support

**Comment by Indignator** [comment]
Sorry i forgot to mension that the error persists

**Comment by linkanon** [comment]
What does the log say now after you whitelisted the .dll, put it back where it should be and restarted your PC?

**Comment by Indignator** [comment]
The same message.

**Comment by linkanon** [comment]
- Move your AAU folder under `D:\Games\CoisasAA2`
- Run the Install.bat
- if it pops up and disappears run it directly from the command line(or add `Pause` at the end of it) and post what it says there and in the logfile.txt

**Comment by Indignator** [comment]
Ok, now it worked, thank you.
