### ISSUE TITLE
3P H crash

### ISSUE THREAD

**Issue by ClockResonator** [aa2g/AA2Unlimited#93]
Just like the title says, the game crashes when attempting to 3P, although it does it after dialogue when the H-Scene would normaly start.
https://mega.nz/fm/qooy3BKR
I uploaded the .rar with the crash on mega, though my aaucrash.dmp was in the AA2 folder instead of being in the AAUnlimited folder. (not sure if this matters)

**Comment by geneishouko** [comment]
The link is only usable by you. You have to share a link with the key.

**Comment by ClockResonator** [comment]
What key? I think ik what made the link unusable, I used add a link 1st now I tried it without that and it works or atleast should work.

**Comment by geneishouko** [comment]
It only works for you, no one else. Anyway, I fixed an important 3P crash that is very likely to be the same as yours. It should be up in the next update.

**Comment by ClockResonator** [comment]
Ok thx for the info.
