### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by AoiRice** [aa2g/AA2Unlimited#94]
I keep getting a recurring crash that happens at seemingly random times, usually when I'm viewing a character in the Roster screen or initiating a conversation in game. I can usually get into 10-20 mins of the game without any problems but I eventually encounter the crash error.

This is the error I receive- 
Unhandled Exception  Code: 0xC0000005  Address: 0x0117C806

I appreciate whatever help I can get from y'all, thanks.

**Comment by Maleboulge** [comment]
I have the same issue, but diffrent adress. Did you figure it out? 

Adding crash dump and image for dev.

![uten navn](https://user-images.githubusercontent.com/38435726/38828790-6b6b94d4-41b7-11e8-9d38-b00a9371ea0c.png)

**Comment by AoiRice** [comment]
I think the problem has something to do with the hair of the female students, I noticed that when I created a completely new class set, the only time my game is crashing is when I'm playing with the class that uses certain hair from the HEXA hair pack. I know another question that got solved here had a similar problem and one of the devs claimed it had something to do with the hair. Idk man, I could be wrong.

**Comment by Maleboulge** [comment]
You might be right on it, after replacing a few students my game started to work better (two of the students had hexa hair). Probably worth to add that my game seemed more prone to crash when i was checking the statue, but at times the roster also caused it. No problem now though.

**Comment by linkanon** [comment]
Most likely it crashed trying to free memory.
Try using safer values for the .pp2 settings: suggested default is `800/200/200`.
After you get comfortable with these numbers you can start experimenting. You can raise the third number until the game becomes unstable but you might get better loading times. Either find that sweet spot or just keep defaults if you just want it to work
