### ISSUE TITLE
Can't install AA2Unlimited

### ISSUE THREAD

**Issue by Rainy1403** [aa2g/AA2Unlimited#95]
Hello dev(s), I'm new here.
I can't install AA2Unlimited, when I click "Install.bat" it show up the error in the picture I attach below.
Can you help me solve this problem? I'm using Windows 10.

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/38882007/39471234-3cd61b1a-4d6c-11e8-85a5-bbae1dc70ca0.png">
<img width="960" alt="untitled2" src="https://user-images.githubusercontent.com/38882007/39471235-3d0d3a5a-4d6c-11e8-9736-e8dffebd7a7d.png">

**Comment by overwritten** [comment]
That's happened to me too. It appears the AAUnlimitedDLL.dll file isn't in any part of the directory, which has me confused... I don't know where to get another one from, either, so I'm stumped like you are.

**Comment by Ashikru** [comment]
Yep, getting the same issue. Hopefully someone figures out the issue before long. >.>

**Comment by geneishouko** [comment]
Glad you both got the issue fixed.

Rather than downloading that dll from some organization unaffiliated to Microsoft, I'd prefer if you went to the official download page and tried to repair your [Visual C++ 2015 Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=52685) installation

I'll keep this issue open so that others may easily find your solutions.

**Comment by HM03surf** [comment]
The alt patcher says "Can't find AAUnlimitedDLL.dll in this folder."

And install.bat says "AAUnlimitedDLL.dll is not a valid Win32 application."

**Comment by geneishouko** [comment]
Did you install Visual C++ 2015 Runtime as described by the requirements list?

**Comment by HM03surf** [comment]
@geneishouko Yes I have both x64 and x86 types of Visual C++ 2015 Redistributable version 14.0.24210 installed. I am using a Windows 7 with Service Pack 1 and my Artificial Academy 2 game has both Append sets with the latest patches (Hongfire Patch 4.11 and HF DLC Patch 1.0.7) I unpacked the AAUnlimited v1.0.2 folder into the game's directory Illusion/AA2Play and double clicked install.bat as stated by the instructions in Google Documents. The command prompt appears and runs AAUnlimitedDll.dll and after a second displays the error message "AAUnlimitedDLL.dll is not a valid Win32 application." I downloaded alt_patcher.exe as provided in the releases section and placed it in the AAUnlimited folder. The alt_patcher.exe runs for a second and provides the message "Can't find AAUnlimitedDLL.dll in this folder." A patcher window never opens as a result.

**Comment by ezdiy** [comment]
If AAUnlimitedDLL.dll truly isn't anywhere to be found (it should be in same directly alt patcher or bat installer is run from), your av has deleted it.

Fix is simple, make your av software not delete files spuriously without your consent.

**Comment by HM03surf** [comment]
@ezdiy AAUnlimitedDLL.dll is present in the folder. lib/lua53.dll has not been deleted by my antivirus software. I downloaded the AAUnlimited_v1.0.2.7z again and used the Open Archive command to make sure none of the files were deleted suddenly upon extraction, and all of the files were accounted for.  I have not found a file titled "liblua*.dll" in either the 7zip file, extracted files, or my antivirus quarantine, so I will presume lib/lua53.dll, lib/cdlua53.dll, lib/imlua53.dll, or lib/iuplua53.dll are the files you are referring to.

**Comment by joseelpro718** [comment]
i have the same problem... i try to instal AA2Unlimited but says AA2UnlimitedDll.dll cant find in this folder, and the alt_patcher says the same i have installed visual cc+ 2015 but says the same

**Comment by kirasisi** [comment]
Hi, I got this problem while installing AA2Unlimited
[CRITICAL ERROR] error loading module 'iuplua' from file 'D:\AAUnlimited\lib\iuplua53.dll':
	The specified module could not be found.

**Comment by Scout25DA** [comment]
> Hello dev(s), I'm new here.
> I can't install AA2Unlimited, when I click "Install.bat" it show up the error in the picture I attach below.
> Can you help me solve this problem? I'm using Windows 10.
> 
> <img alt="untitled" width="960" src="https://user-images.githubusercontent.com/38882007/39471234-3cd61b1a-4d6c-11e8-85a5-bbae1dc70ca0.png">
> 
> <img alt="untitled2" width="960" src="https://user-images.githubusercontent.com/38882007/39471235-3d0d3a5a-4d6c-11e8-9736-e8dffebd7a7d.png">

Try to rename your folder to english and use your regedit find "HKEY_CURRENT_USER\Software\ILLUSION\AA2Play" and "HKEY_CURRENT_USER\Software\ILLUSION\AA2Edit" and rename the "INSTALLDIR"'s value to the path of your games like for example AA2Play to AA2Play and AA2Edit to AA2Edit.

**Comment by Escuti** [comment]
Guys, i still have the same problem. I've tried EVERYTHING and nothing seems to work. I've used the AltPatcher, i've reinstalled the game, i've changed the regedit, i've tried the Visual C update,.. And everythings still doesn't work.

**Comment by linkanon** [comment]
With all those attempts chances are you borked your current install. There's little actual reason to mod the game from scratch so I suggest getting the AA2Mini version. Follow this guide and you should be up to date in no time https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0

**Comment by k4yf0ur** [comment]
Consider following [this ](url
![image](https://docs.google.com/spreadsheets/d/19W3k7_S-G6sJas7cTaN525l4ZCVCn0g0UxlAxNIl8pc/edit#gid=0) guide.
